bcgov/DriveBC.ca

- src/frontend/src/App.js
- src/frontend/src/App.scss
- src/frontend/src/Components/Layers.scss
- src/frontend/src/Components/Map.scss
- src/frontend/src/Components/Routes.scss
- src/frontend/src/Components/cameras/CameraList.js
- src/frontend/src/Components/cameras/CameraList.scss
- src/frontend/src/Components/cameras/WebcamCard.js
- src/frontend/src/Components/cameras/WebcamCard.scss
- src/frontend/src/Footer.scss
- src/frontend/src/PageHeader.js
- src/frontend/src/PageHeader.scss
- src/frontend/src/pages/CamerasPage.js
- src/frontend/src/pages/StylesPage.js
- src/frontend/src/styles/bootstrap-customizations.scss
- src/frontend/src/styles/typography.scss
- src/frontend/src/styles/variables.scss
Added styling for webcam list page.
> DBC22-346: Added styling for webcam list page

- src/backend/apps/feed/serializers.py
- src/frontend/src/Components/cameras/WebcamCard.js
- src/frontend/src/Components/cameras/WebcamCard.scss
- src/frontend/src/pages/CameraDetailsPage.js
And Refactoring Webcam cards code
> DBC22-434: Added conditional states for webcams on webcam details page

- src/frontend/src/App.js
- src/frontend/src/App.scss
- src/frontend/src/CameraDetailsPage.scss
- src/frontend/src/Components/Layers.js
- src/frontend/src/Components/Map.js
- src/frontend/src/Components/Map.scss
- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/MapPage.js
First push to set up map window in camera details, additional features and routing logic in progress
> DBC22-597: Code cleanup and initial map window

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/Components/Map.js
- src/frontend/src/Components/Map.scss
- src/frontend/src/pages/CameraDetailsPage.js
Took longer than I thought to setup routing since I decided to remove the existing popup component we were using and design it from scratch for better control, now we have routing to the details page and better control over the popup state and design.
> DBC22-638: Rebuilt map popup with default css and routing

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/Components/events/EventCard.js
- src/frontend/src/Components/events/EventCard.scss
- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/events/EventsTable.scss
- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/pages/EventsPage.js
- src/frontend/src/pages/EventsPage.scss
- src/frontend/src/styles/bootstrap-customizations.scss
- src/frontend/src/styles/variables.scss
DBC22-657: Event list mobile component rendering and styling
DBC22-657: Updated events table styles
> Feature/DBC22-657: Event list mobile component rendering and styling

- src/frontend/src/Header.js
- src/frontend/src/pages/CameraDetailsPage.js
Setting Nav.link the false allows the LinkContainer component to control the active state for the tabs, fixing the issue as reported in the bug.
> DBC22-676: Active state disabled on Nav.link

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/Footer.js
- src/frontend/src/Footer.scss
- src/frontend/src/Header.js
> DBC22-456: Updated nav and footer

- src/frontend/src/Footer.scss
Updated footer background and social media hover background.
> DBC22-757: updated footer background and social media hover background

- .pre-commit-config.yaml
- src/frontend/.eslintrc.js
- src/frontend/.prettierrc
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/App.js
- src/frontend/src/Components/Advisory.js
- src/frontend/src/Components/Layers.js
- src/frontend/src/Components/Routes.js
The previous PR was lacking some setup that this revision adds, now pre-commit hooks and prettier should be better integrated with Eslint
> DBC22-736: Additional Eslint fixes and pre-commit adjustment

- src/frontend/src/Components/Map.js
Added my location pin point on the map
> DBC22-718: Added my location pin point on the map

- src/frontend/src/Components/Map.js
Set my location to the center of BC for users outside of BC
> DBC22-932: set my location to the center of BC for users outside of BC

- .github/workflows/dev.yml
- .github/workflows/test.yml
- .github/workflows/uat.yml
Split static and backend build & Deploys into two separate jobs
> DBC-1091: Split github action steps into jobs

- src/frontend/src/Header.js
Navigate to current site when logo clicked
> DBC22-1095: Navigate to current site when logo clicked

- src/frontend/src/Components/events/EventsTable.js
Updated tooltip according to the description
> DBC22-1104: Updated tooltip according to the description

- src/frontend/src/Components/map/mapPopup.js
DBC22-948: Updated direction text on delay popup
> DBC22-948: Updated direction text on delay popup

- src/frontend/src/Components/Map.js
DBC22-1056: Fixed the precision accurate issue in different zoom level
> DBC22-1056: Fixed the precision accurate issue in different zoom level

- src/frontend/src/Components/advisories/AdvisoriesAccordion.js
DBC22-1259: Show advisory when there are advisories
> DBC22-1259: Show advisory when there are advisories

- infrastructure/crunchy-postgres/values-dev.yaml
- infrastructure/crunchy-postgres/values-prod.yaml
- infrastructure/crunchy-postgres/values-test.yaml
- infrastructure/crunchy-postgres/values-uat.yaml
Increase space in the crunchy db clusters
> DBC22-1298 - Give more space to Crunchy DB in the HELM Charts

- src/frontend/src/Components/Map.js
DBC22-1308: Echo zoom level whenever map got updated
> DBC22-1308: Echo zoom level whenever map got updated

- src/frontend/src/Components/map/helper.js
regression bug, as it seems to have been removed in a recent merge.
> DBC22-940: re-added alt text for my location pin on map

- src/frontend/src/Components/cameras/CameraList.js
- src/frontend/src/Components/cameras/WebcamCard.js
DBC22-642: use session to store previous page position
> DBC22-642: use session to store previous page position

- src/frontend/src/pages/CameraDetailsPage.js
DBC22-1322: set infinite to false to prevent replay repeatedly
> DBC22-1322: set infinite to false to prevent replay repeatedly

- .env.example
- src/backend/apps/shared/views.py
DBC22-1326: using django pod environment variables for route planner
> DBC22-1326: using django pod environment variables for route planner

- src/frontend/src/Components/Map.js
- src/frontend/src/Components/cameras/WebcamCard.js
- src/frontend/src/Components/map/helper.js
- src/frontend/src/Components/map/layers/camerasLayer.js
- src/frontend/src/Components/map/layers/eventsLayer.js
- src/frontend/src/Components/map/mapPopup.js
- src/frontend/src/pages/CameraDetailsPage.js
New PR to rebase and start fresh from the new changes to main
> DBC22-1157 + 1112: added view camera and event list-to-map logic

- infrastructure/main/values-prod.yaml
- infrastructure/main/values-uat.yaml
To temporarily resolve issues with Huey jobs getting stuck
> bugfix/DBC22-1359: Reduce redis replicas to 1 in UAT and PRD

- src/frontend/src/Components/Filters.js
- src/frontend/src/Components/Filters.scss
- src/frontend/src/Components/Map.js
- src/frontend/src/Components/Map.scss
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/pages/EventsPage.js
- src/frontend/src/pages/EventsPage.scss
would need some help to put back filters functionality with the reusable components instead of the Bootstrap dropdown component.
> DBC22-1047: refactor and reusing filters on Delays page

- src/frontend/src/Components/data/featureStyleDefinitions.js
- changed delay route style to _not_ red
- updated icon offset to remove icon shifting when active state is enabled
> update route colour and icon anchors

- src/frontend/src/pages/CameraDetailsPage.js
DBC22-1520: Preload image when replay the day to prevent strobing
> DBC22-1520: Preload image when replay the day to prevent strobing

- .github/workflows/codetest-sonarcloud.yml
- .github/workflows/sonarcloud.yml
- src/backend/apps/feed/tests/test_event_feed_parse.py
- src/backend/apps/feed/tests/test_webcam_feed_parse.py
feature/DBC22-1709: Add code testing
> feature/DBC22-1709: Add code testing

- src/frontend/src/Components/Map.scss
- src/frontend/src/Components/map/mapPopup.js
- src/frontend/src/Components/map/mapPopup.scss
DBC22-1813: updated events side panel styling according to the design
> DBC22-1813: updated events side panel styling according to the design

- src/frontend/src/Components/Map.scss
- src/frontend/src/Components/map/mapPopup.scss
- updated sidepanel width
- hover state for friendly time
- hover state, position, and colour fix for sidepanel close button
- minor events border top fix
> sidepanel qa updates

- src/frontend/src/Components/map/RouteSearch.scss
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/pages/EventsListPage.scss
Additional fixes for styling on the delays and cameras list pages
> DBC22-1880: adjusted styling for delays and cameras pages

- src/frontend/src/Components/EventTypeIcon.js
DBC22-1747: added alt text for delay icons for JAWS reading
> DBC22-1747: added alt text for delay icons for JAWS reading

- src/frontend/src/Components/Map.js
DBC22-1903: set aria-hidden when side panel invisible
> DBC22-1903: set aria-hidden when side panel invisible

- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/Components/bulletins/BulletinsList.js
DBC22-1867: added tabIndex to make advisory/bulletin focusable
> DBC22-1867: added tabIndex to make advisory/bulletin focusable

- src/frontend/src/pages/CameraDetailsPage.js
DBC22-1672: added aria-label for control buttons on replay the day
> DBC22-1672: added aria-label for control buttons on replay the day

- src/frontend/src/Components/map/mapPopup.scss
DBC22-2009: updated to all capitalized name for rest stops
> DBC22-2009: updated to all capitalized name for rest stops

- src/backend/apps/event/serializers.py
- src/frontend/src/Components/EventTypeIcon.js
DBC22-2075: return future delays for planned closures
> DBC22-2075: return future delays for planned closures

- src/frontend/src/Components/events/EventTypeIcon.js
- src/frontend/src/Components/map/helpers/events.js
DBC22-2075: display future planned closure as future delays
> DBC22-2075: display future planned closure as future delays

- compose/frontend/default.conf
- src/frontend/src/App.js
Needed to make a few minor changes to App.js so it would work with the csp as per: https://docs.fontawesome.com/web/use-with/react/use-with
> DBC-2155: Add Content Security Policy

- src/frontend/src/Components/map/overrides.js
basemap theming overrides for public beta
> updated basemap styles

- src/frontend/src/Components/map/Map.js
Only showing the advisories in view (within viewport) on desktop, and showing all advisories on mobile
> DBC22-2244: Changed to show all advisories on mobile

- src/frontend/public/maintenance/maintenance.html
Also updated the page a bit so that the footer always stays at the bottom of the screen.
> DBC22-2285: Address Sonarcloud finding

- src/frontend/src/App.js
- src/frontend/src/pages/ProblemsPage.js
- src/frontend/src/pages/ProblemsPage.scss
DBC22-2277: added frontend problem report landing page
> DBC22-2277: added frontend problem report landing page

- compose/frontend/default.conf
- compose/frontend/default_maintenance.txt
- infrastructure/_django/templates/django-deployment.yaml
- infrastructure/_static/templates/static-deployment.yaml
- infrastructure/main/values-dev.yaml
- infrastructure/main/values-prod.yaml
- infrastructure/main/values-test.yaml
- infrastructure/main/values-uat.yaml
Adding Readiness probe for nginx and Django.
Also updated resource values for task and django pods as they were a bit under resourced in dev/test especially.
> DBC22-2305 & DBC22-2312: Add healthcheck

- src/backend/apps/feed/serializers.py
NOTE: If there are any entries in the DB containing &#39; those entries will need to be removed using a SQL script so they can get added back correctly.
Usually events come and go fairly quick, so don't expect this to be much of an issue.
> DBC22-1953: Handle html apostrophe coming from DIT

- src/frontend/src/Header.js
Added before and after screenshots:
> DBC22-2334: Feedback button on mobile positioned correctly

- src/backend/apps/authentication/adapters.py
- src/backend/apps/authentication/urls.py
- src/backend/apps/authentication/views.py
- src/backend/apps/shared/api.py
- src/backend/apps/shared/views.py
- src/backend/config/settings/django.py
- src/backend/config/settings/third_party.py
- src/backend/config/urls.py
- src/backend/requirements/base.txt
- src/frontend/src/App.js
- src/frontend/src/Header.js
- src/frontend/src/Header.scss
- src/frontend/src/Modal.js
- src/frontend/src/Modal.scss
- src/frontend/src/pages/AccountPage.js
- src/frontend/src/pages/AccountPage.scss
This PR adds features requiring the following environment variables:
BCEID_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/standard
BCEID_CLIENT_ID=_see Password Manager Pro_
BCEID_SECRET=_see Password Manager Pro_
> DBC22-2122

- src/backend/apps/event/serializers.py
- src/frontend/src/Components/events/functions.js
- src/frontend/src/Components/map/handlers/click.js
- src/frontend/src/Components/map/panels/EventPanel.js
- src/frontend/src/Components/map/panels/EventPanel.scss
Fixed styling and vocabulary; icons to be updated later.
> DBC22-2283

- src/backend/apps/weather/serializers.py
- src/frontend/.eslintrc.js
- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/handlers/click.js
- src/frontend/src/Components/map/handlers/hover.js
- src/frontend/src/Components/map/layers/currentWeatherLayer.js
- src/frontend/src/Components/map/layers/ferriesLayer.js
- src/frontend/src/Components/map/layers/index.js
- src/frontend/src/Components/map/layers/largeRestStopsLayer.js
- src/frontend/src/Components/map/layers/regionalWeatherLayer.js
- src/frontend/src/Components/map/layers/restStopsLayer.js
- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/Components/map/panels/EventPanel.js
- src/frontend/src/Components/map/panels/FerryPanel.js
- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Components/map/panels/index.js
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.js
- src/frontend/src/Components/shared/ShareURLButton.js
- src/frontend/src/Components/shared/ShareURLButton.scss
- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/MapPage.js
[DBC22-2329](https://jira.th.gov.bc.ca/browse/DBC22-2329)
Note that the ticket/story only specified sharing events but this implementation includes all clickable, layered features on the map that opens a panel, with the exception of advisories.
> DBC22-2329: reworked panel navigation and added copy button

- compose/frontend/default.conf
https://jira.th.gov.bc.ca/browse/DBC22-2429
updates default.conf to allow for the login functionality to work.
> DBC22-2429: Proxy requests for user login

- src/frontend/src/App.scss
- src/frontend/src/Components/advisories/AdvisoriesList.scss
- src/frontend/src/pages/AdvisoriesListPage.scss
- src/frontend/src/pages/AdvisoryDetailsPage.scss
- src/frontend/src/pages/BulletinsListPage.scss
https://jira.th.gov.bc.ca/browse/DBC22-1662
Minor change to spacing for bulletins and advisories.
> DBC22-1662: Fix spacing in advisory/bulletins

- src/backend/apps/weather/management/commands/populate_winter_sawsx_data.py
- src/backend/apps/weather/serializers.py
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.scss
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.scss
- src/frontend/src/Components/shared/FriendlyTime.js
[DBC22-2419](https://jira.th.gov.bc.ca/browse/DBC22-2419)
Local weather updates as shown in today's sprint review prep
> DBC22-2419: styling and hourly forecast for local weather

- src/frontend/src/Components/map/overrides.js
- src/frontend/src/Components/map/panels/weather/ForecastCarousel.js
- src/frontend/src/Components/map/panels/weather/ForecastCarousel.scss
- src/frontend/src/Components/map/panels/weather/ForecastTabs.js
- src/frontend/src/Components/map/panels/weather/ForecastTabs.scss
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.scss
- includes a map fix from Volker
- updates style/interactive states for weather side panel
- includes a fix for special advisory on weather panel as well
> weather sidepanel updates

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/routing/RouteDetails.js
[DBC22-2526](https://jira.th.gov.bc.ca/browse/DBC22-2526)
> DBC22-2526: fixed route search panel interactions

- .github/workflows/codetest-sonarcloud.yml
https://jira.th.gov.bc.ca/browse/DBC22-2545
Confirmed fixed on my test branch.
> DBC22-2545: Fix for unit test github action

- src/frontend/src/Components/report/ReportMap.js
- src/frontend/src/Components/report/ReportMap.scss
https://jira.th.gov.bc.ca/browse/DBC22-2431
Bug fix to add the CONTRACTOR DESCRIPTION to the RAHP. This is mostly an issue for Kelowna region as there is a special contractor just for the bridge.
I reviewed the styling with Chris (since James is away) and he confirmed it looked good.
> DBC22-2431:Add contractor description to RAHP

- src/frontend/src/expireReducer.js
[DBC22-2565](https://jira.th.gov.bc.ca/browse/DBC22-2565)
> DBC22-2565: disable caching in redux

- src/frontend/src/Components/events/EventCard.scss
- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/events/EventsTable.scss
- src/frontend/src/Components/map/panels/EventPanel.js
- src/frontend/src/Components/map/panels/EventPanel.scss
- src/frontend/src/Components/shared/FriendlyTime.js
- src/frontend/src/Components/shared/FriendlyTime.scss
For https://jira.th.gov.bc.ca/browse/DBC22-2407
> DBC22-2407: Handle overdue updates for delays

- src/frontend/src/Components/routing/RouteDetails.js
[DBC22-2570](https://jira.th.gov.bc.ca/browse/DBC22-2570)
> DBC22-2570: default input for route panel nickname

- src/frontend/src/Components/cameras/CameraList.js
- src/frontend/src/Components/shared/HighwayFilter.js
- src/frontend/src/Components/shared/HighwayFilter.scss
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/slices/highwayFilterSlice.js
- src/frontend/src/slices/index.js
- src/frontend/src/store.js
Note: there are still two bugs remaining with this component: one being that the highway list is not re-rendering with search input currently, and the cameras list is not re-rendering when the remove selected highway button is pressed.
> DBC22-2403: Added Highway Filter component and logic

- src/frontend/src/Components/map/panels/EventPanel.js
- src/frontend/src/Components/map/panels/FerryPanel.js
- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Components/map/panels/index.scss
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.scss
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.js
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.scss
- src/frontend/src/Components/shared/ShareURLButton.scss
- src/frontend/src/styles/variables.scss
Feature/dbc22-2468: rework on existing branch
> Feature/dbc22-2468: rework on existing branch

- src/frontend/src/App.js
- src/frontend/src/Components/shared/header/UserNavigation.js
[DBC22-2524](https://jira.th.gov.bc.ca/browse/DBC22-2524)
Tested across two browsers - saving a new cam on a new browser will be reflected on the old browser on refresh.
This was another case of me subconsciously doing premature optimization. I'll pay extra attention to avoiddown the line.
> DBC22-2524: saved cams and routes now update on every refresh

- src/backend/apps/weather/serializers.py
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
https://jira.th.gov.bc.ca/browse/DBC22-2478
Added wind direction to average wind speeds. Also rounded the average and max winds.
> DBC22-2478: Add wind direction to local weather

- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
https://jira.th.gov.bc.ca/browse/DBC22-2298
Simply added an m after the elevation data in the popup
> DBC22-2298: Add unit to elevation

- src/backend/apps/feed/client.py
https://jira.th.gov.bc.ca/browse/DBC22-2586
Issue was related to SAWSx not appending timezone data, so had to set time zone to UTC manually.
> DBC22-2586: Fix time zone issue for SAWSx weather

- src/frontend/src/App.scss
- src/frontend/src/Components/cameras/CameraCard.scss
- src/frontend/src/Components/cameras/CameraList.scss
- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/events/EventsTable.scss
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/Components/shared/header/UserNavigation.scss
- src/frontend/src/pages/SavedRoutesPage.js
- src/frontend/src/pages/SavedRoutesPage.scss
- src/frontend/src/styles/bootstrap-customizations.scss
- Transition on hover over saved routes card on saved routes page
- Transition on click for view saved cameras on saved routes page
- minor fixes and consistency style application on buttons throughout the site
> DBC22-2519: Added hover and transition animations on saved routes page

- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
DBC22-2585: added loading stages for camera details page
This PR added loading stages to camera details page. It reused the implementation in Event list page, shows skeletons when the camera image is still loading.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-2585
> DBC22-2585: added loading stages for camera details page

- src/frontend/src/App.scss
- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.scss
Small style tweaks and UI change for https://jira.th.gov.bc.ca/browse/DBC22-2544
> DBC22-2544: Style updates for Save UI

- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/cameras/CameraCard.scss
- src/frontend/src/Components/cameras/CameraList.js
- src/frontend/src/Components/cameras/HighwayGroup.js
- src/frontend/src/Components/data/locations.js
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/routing/RouteSearch.js
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/EventsListPage.js
DBC22-2584: added loading stages for camera list page
This PR added loading stages to camera list page. It reused the implementation in Event list page, shows skeletons when the camera images are still loading.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-2584
> DBC22-2584: added loading stages for camera list page

- src/frontend/src/Components/cameras/CameraCard.scss
- src/frontend/src/Components/cameras/CameraList.scss
- src/frontend/src/Components/events/EventsTable.scss
- src/frontend/src/Components/map/panels/CamPanel.scss
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/Components/routing/RouteSearch.scss
- src/frontend/src/Components/shared/ShareURLButton.scss
- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.scss
- src/frontend/src/pages/SavedCamerasPage.scss
- src/frontend/src/pages/SavedRoutesPage.scss
qa updates to:
- sidepanel share button
- added space between rows in camera list page
- added hover states for camera list cards (view map, save/remove)
- removed border-right from table header in events
- removed tr outline on focus in events page
- added max-width to container in my cams/routes pages
- updated "search cameras" input height
> design qa updates

- src/backend/apps/feed/client.py
- src/backend/apps/weather/serializers.py
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js
https://jira.th.gov.bc.ca/browse/DBC22-2627
1. Change Precipitation to pull from pcpn_amt_pst1hr
2. Change Snow to pull from snwfl_amt_pst1hr
3. Added preciptitation_stdobs to pull from pcpn_amt_snc_std_obs
4. Added snow_stdobs to pull from snwfl_amt_snc_std_obs  
5. Updated average_wind to pull from  mean_wnd_spd_pst1hr
6. Updated wind_direction to pull from mean_wnd_dir_pst1hr
7. Grouped Precipitation hourly and since 6am/6pm like we do for wind (Chris suggested we show both hourly and stdobs)
8. Grouped Snow hourly and since 6am/6pm like we do for wind (Chris suggested we show both hourly and stdobs)
9. Round all those values to nearest decimal place (ie 1.2), but if 0 make sure there is no decimals.
10. Ensure there are no negative values returned to end user
> DBC22-2627: Update Weather Data

- src/frontend/src/App.js
- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/shared/Alert.js
- src/frontend/src/Components/shared/Alert.scss
- src/frontend/src/Components/shared/ShareURLButton.js
- src/frontend/src/pages/CameraDetailsPage.js
[DBC22-2557](https://jira.th.gov.bc.ca/browse/DBC22-2557) / [DBC22-2599](https://jira.th.gov.bc.ca/browse/DBC22-2599)
Reworked the Alert component to be controlled via importing AlertContext from App.js.
> DBC22-2557/DBC22-2599: Alert rework and animations

- src/backend/apps/feed/client.py
[DBC22-2373](https://jira.th.gov.bc.ca/browse/DBC22-2373)
The cause of this was likely a side effect from [DBC22-2126](https://jira.th.gov.bc.ca/browse/DBC22-2126) which removes stations that have empty data. I've changed the code to specifically target VMS only.
> DBC22-2373: revised VMS fix to not affect other stations

- src/frontend/src/App.scss
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/pages/EventsListPage.scss
https://jira.th.gov.bc.ca/browse/DBC22-2669
> DBC22-2669: Updated pages to have consistent container breakpoints

- src/frontend/src/Components/map/Map.js
Highway symbols are now separately visible in a topmost layer, preventing icons and routes from obscuring them.
> DBC22-1610

- src/frontend/src/App.scss
- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/data/webcams.js
- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/pages/CameraDetailsPage.js
Fixes bug in highlighting orientations, establishes order for listing orientations.
> DBC22-1538, DBC-1413

- infrastructure/crunchy-postgres/values-dev.yaml
- infrastructure/crunchy-postgres/values-prod.yaml
- infrastructure/crunchy-postgres/values-test.yaml
- infrastructure/crunchy-postgres/values-uat.yaml
https://jira.th.gov.bc.ca/browse/DBC22-2504
> DBC22-2504: Update retention periods for crunchy

- src/frontend/src/Components/map/helpers/map.js
DBC22-2653: fixed my location spinner does not disappear when denied by user
> DBC22-2653: fixed my location spinner does not disappear when denied by user

- src/frontend/src/Components/map/helpers/map.js
- src/frontend/src/pages/EventsListPage.js
This PR used localStorage to save selected sorting key, to fix the issue that the selected sort option does not retained.
> DBC22-2151: used localStorage to save selected sorting key

- src/frontend/src/Components/map/overrides.js
- src/frontend/src/Components/routing/RouteMap.js
- src/frontend/src/pages/AdvisoryDetailsPage.js
Added override code to advisory details page and route map generation.
Included whitespace fixing in overrides.js
> DBC22-2700

- src/frontend/src/Components/shared/header/UserNavigation.js
https://jira.th.gov.bc.ca/browse/DBC22-2671
> DBC22-2671: Added title to be ready by screen reader for icon-only button.

- src/frontend/public/index.html
https://jira.th.gov.bc.ca/browse/DBC22-2749
Just updating site description so we are not requesting site feedback.
> DBC22-2749: Update site description

- src/frontend/src/Components/map/Map.js
DBC22-2131: removed pin overlay when search location is cleared up
> DBC22-2131: removed pin overlay when search location is cleared up

- src/frontend/src/App.scss
- src/frontend/src/Components/map/layers/regionalWeatherLayer.js
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.js
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.scss
[DBC22-2396](https://jira.th.gov.bc.ca/browse/DBC22-2396)
This only affects regional weather stations. Local weather stations will be handled at a later time, but it likely won't be needed as there are no local weather stations that don't show either air or ground temp.
> DBC22-2396: missing info display for regional weather

- src/frontend/src/Components/shared/header/Header.js
DBC22-2461: moved sign in/out button to correct position
> DBC22-2461: moved sign in/out button to correct position

- src/frontend/src/Components/map/layers/currentWeatherLayer.js
- src/frontend/src/Components/map/layers/ferriesLayer.js
- src/frontend/src/Components/map/layers/regionalWeatherLayer.js
- src/frontend/src/Components/map/layers/restStopsLayer.js
[DBC22-2549](https://jira.th.gov.bc.ca/browse/DBC22-2549)
[DBC22-2353](https://jira.th.gov.bc.ca/browse/DBC22-2353)
[DBC22-2498](https://jira.th.gov.bc.ca/browse/DBC22-2498)
Offsetting features in various layers to prevent overlaps.
> DBC22-2549: offset weather stations/rest stops/ferries for overlaps

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/shared/header/Header.js
[DBC22-2520](https://jira.th.gov.bc.ca/browse/DBC22-2520)
> DBC22-2520: exit survey changes

- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/Components/map/panels/AdvisoriesPanel.js
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/pages/AdvisoriesListPage.js
- src/frontend/src/pages/AdvisoryDetailsPage.js
- src/frontend/src/pages/BulletinDetailsPage.js
- src/frontend/src/pages/BulletinsListPage.js
[DBC22-2724](https://jira.th.gov.bc.ca/browse/DBC22-2724)
> DBC22-2724: saved items now use id and live_revision as identifier

- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Components/map/panels/RestStopPanel.scss
- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/Modal.js
- src/frontend/src/Modal.scss
- src/frontend/src/pages/EventsListPage.scss
https://jira.th.gov.bc.ca/browse/DBC22-2729 and https://jira.th.gov.bc.ca/browse/DBC22-2136
> DBC22-2729: Worked on accessibility for tooltips

- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Modal.js
https://jira.th.gov.bc.ca/browse/DBC22-2729
> DBC22-2729: Update accessible content for tooltips

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/MapWrapper.js
- src/frontend/src/Components/map/dataLoaders/advisories.js
- src/frontend/src/Components/map/dataLoaders/cameras.js
- src/frontend/src/Components/map/dataLoaders/currentWeathers.js
- src/frontend/src/Components/map/dataLoaders/events.js
- src/frontend/src/Components/map/dataLoaders/ferries.js
- src/frontend/src/Components/map/dataLoaders/regionalWeathers.js
- src/frontend/src/Components/map/dataLoaders/restStops.js
- src/frontend/src/Components/map/filterRouteWorker.js
- src/frontend/src/Components/map/helpers/spatial.js
- src/frontend/src/Components/map/layers/camerasLayer.js
- src/frontend/src/Components/map/layers/currentWeatherLayer.js
- src/frontend/src/Components/map/layers/eventsLayer.js
- src/frontend/src/Components/map/layers/ferriesLayer.js
- src/frontend/src/Components/map/layers/index.js
- src/frontend/src/Components/map/layers/largeRestStopsLayer.js
- src/frontend/src/Components/map/layers/regionalWeatherLayer.js
- src/frontend/src/Components/map/layers/restStopsLayer.js
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteMap.js
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/SavedCamerasPage.js
[DBC22-1605](https://moti-imb.atlassian.net/browse/DBC22-1605)
- Map layers/features are no longer removed/added on updating route
- Added web worker for map loading operations. Loading is faster and does not block the main thread.
TODO:
- Apply same changes to other pages on the site
- Make one single webwoker available globally across different pages?
> DBC22-1605: loading rework in map with web worker

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/errors/StaleLinkError.js
- src/frontend/src/Components/map/errors/StaleLinkError.scss
- src/frontend/src/Components/map/layers/eventsLayer.js
Implements a displayed message when the reference data for an event is not correlated with an active event.
> DBC22-2441 Display message for stale share links

- src/backend/apps/cms/static/readinglevel.js
- src/backend/apps/cms/wagtail_hooks.py
- src/backend/requirements/base.txt
This was work completed earlier but delayed merging due to questions about how to include a non-pip package (one only available as a git repo on github, making us potentially vulnerable to maintainer attacks).  Simplest thing was to duplicate the required code (with appropriate licence terms included).
> DBC22-2130 Add reading level to wagtail editor blocks

- src/frontend/src/Components/map/panels/AdvisoriesPanel.scss
- src/frontend/src/pages/ContainerSidePanel.scss
After consultation with James Byun, the entire side panel scrolls now.
> DBC22-2841 Make advisories panel scroll

- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-2777
> DBC22-2777: Changed image fit to show pre-processed timestamp

- infrastructure/main/values-dev.yaml
- infrastructure/main/values-prod.yaml
- infrastructure/main/values-test.yaml
- infrastructure/main/values-uat.yaml
- src/backend/apps/feed/tasks.py
https://moti-imb.atlassian.net/browse/DBC22-2929
Needed to update helm charts with update request/limit values to ensure the task pods have enough resources.
Also set the update event job to every minute and the rest stop job to every 24hrs.
> DBC22-2929: Update task pod cron and resources

- src/frontend/src/App.scss
- src/frontend/src/pages/AdvisoriesListPage.js
- src/frontend/src/pages/AdvisoriesListPage.scss
- src/frontend/src/pages/BulletinDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-2851
> DBC22-2851: Visual enhancements to Advisories and Bulletins pages

- .github/workflows/trivyscans.yml
Fix to prevent rate limiting on the trivy side.
> DBC22-2979:Update trivyscans.yml 

- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/cameras/CameraCard.scss
- src/frontend/src/Components/map/panels/CamPanel.scss
- src/frontend/src/Components/map/panels/index.scss
- src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.scss
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/styles/variables.scss
For https://moti-imb.atlassian.net/browse/DBC22-2602
> DBC22-2602: Style updates to Camera list cards and sidepanel

- src/frontend/src/Components/map/layers/index.js
- src/frontend/src/Components/shared/Filters.js
DBC22-2981: fixed the issue that hef layer not showing up
> DBC22-2981: fixed the issue that hef layer not showing up

- src/frontend/src/pages/BulletinsListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-2851
> DBC22-2851: Style update to Bulletins

- src/frontend/src/Components/map/helpers/location.js
DBC22-2810: adjusted size of the location pin mark as requested. 
Used 44px for the size of existing location pin mark, and used 32px for the size of new added location to pin mark.
> DBC22-2810: adjusted size of the location pin mark as requested

- src/frontend/src/Components/report/ReportMap.scss
- src/frontend/src/pages/ReportRoadPage.scss
DBC22-2830: updated report map styling to allow map scrollable
> DBC22-2830: updated report map styling to allow map scrollable

- src/frontend/src/Components/shared/HighwayFilter.js
DBC22-2933: re-filter ordered highways to avoid undefined value
> DBC22-2933: re-filter ordered highways to avoid undefined value

- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/Components/shared/ShareURLButton.js
DBC22-2842: appended camIndex in the url when sharing camera's URL
> DBC22-2842: appended camIndex in the url when sharing camera's URL

- src/frontend/src/Components/cameras/CameraList.js
DBC22-2832: used index to make sure unique key for highway when rendering
> DBC22-2832: used index to make sure unique key for highway when rendering

- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/panels/RouteDetailsPanel.js
- src/frontend/src/Components/map/panels/RouteDetailsPanel.scss
- src/frontend/src/Components/routing/DistanceLabels.scss
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-2902
> DBC22-2902: Styling alternate routes elements

- .pre-commit-config.yaml
- src/frontend/src/Components/events/EventCard.js
- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/map/filterRouteWorker.js
- src/frontend/src/pages/EventsListPage.js
[DBC22-2846](https://moti-imb.atlassian.net/browse/DBC22-2846): Automatic delay list updates - FE - highlighting changes
- Styling to be done in [DBC22-2968](https://moti-imb.atlassian.net/browse/DBC22-2968)
- Pill displays to be done in [DBC22-2970](https://moti-imb.atlassian.net/browse/DBC22-2970)
When testing locally, I disabled the cache on `EventAPI` (`EVENT_LIST = 0`) and edited the event (last_updated, status) in the database.
> DBC22-2846: Automatic delay list updates

- src/frontend/src/Components/shared/HighwayFilter.scss
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/styles/variables.scss
[DBC22-3023](https://moti-imb.atlassian.net/browse/DBC22-3023) [Figma link](https://www.figma.com/design/Ry0pQCeMrSdg4TZrjQJRSY/DriveBC-Website?node-id=16269-19001&node-type=canvas&t=exv9SKtsqepUYk7D-0)
Desktop
- Nav bar now uses entire screen's width
- Re-added beta feedback btn
- Updated styling for What's new and beta feedback btn
Mobile
- Expanded menu now uses entire screen's height
- Styling updates: background color, right chevron added, spacing/border adjustments
- Added Beta feedback and what's new links
> DBC22-3023: navbar additions and styling updates

- src/backend/apps/weather/serializers.py
https://moti-imb.atlassian.net/browse/DBC22-3022
> DBC22-3022: Fix HEF styling bug

- src/frontend/src/Components/cameras/CameraCard.scss
More enhancement requests via comments on https://moti-imb.atlassian.net/browse/DBC22-2602
> DBC22-2602: Visual enhancements to camera cards

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/helpers/location.js
- src/frontend/src/Components/map/helpers/map.js
DBC22-2810: removed overlays except location from/to pin marks
> DBC22-2810: removed overlays except location from/to pin marks

- src/frontend/src/Components/report/ReportMap.scss
DBC22-3017: set z-index of the close button on the top
> DBC22-3017: set z-index of the close button on the top

- src/frontend/src/Components/events/EventCard.js
- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/map/filterRouteWorker.js
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/EventsListPage.scss
- [DBC22-2969: Automatic delay list updates - FE - pill display for updated items out of viewport](https://moti-imb.atlassian.net/browse/DBC22-2969)
- [DBC22-2970: Automatic delay list updates - FE - styling for pill displays](https://moti-imb.atlassian.net/browse/DBC22-2970)
> DBC22-2969: Pill display for updated items out of viewport

- src/backend/apps/feed/client.py
https://moti-imb.atlassian.net/browse/DBC22-3077
Needed to add the same logic we did for HEF as the regional XML files from Env Canada now also contain Ended warnings.
> DBC22-3077:Remove Ended Env Canada warnings

- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/styles/variables.scss
DBC22-3048: added route notification for filter layers
> DBC22-3048: added route notification for filter layers

- src/frontend/src/Components/routing/DistanceLabels.js
DBC22-3055: push distance labels away when points are too close
> DBC22-3055: push distance labels away when points are too close

- src/backend/apps/rest/tasks.py
DBC22-2870: deleted rest stop records that not available from the rest stop API
> DBC22-2870: deleted rest stop records that not available from the rest stop API

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/handlers/click.js
[DBC22-2756](https://moti-imb.atlassian.net/browse/DBC22-2756)
> DBC22-2756: cam location handler now sets icon to active again in mobile

- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/Components/bulletins/BulletinsList.js
DBC22-2812: sort by last_published_at for advisories and bulletins
> DBC22-2812: sort by last_published_at for advisories and bulletins

- src/frontend/src/pages/ContainerSidePanel.scss
https://moti-imb.atlassian.net/browse/DBC22-3024
> DBC22-3024: Fixed margin to avoid overlap with scrollbar on route switch button.

- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/Components/shared/Filters.scss
https://moti-imb.atlassian.net/browse/DBC22-3123
> DBC22-3123: Fix for filters menu positioning

- src/frontend/src/Components/routing/NoRouteFound.js
- src/frontend/src/Components/routing/NoRouteFound.scss
- src/frontend/src/Components/routing/RouteSearch.js
DBC22-2521: updated messaging when start/end is out of province
> DBC22-2521: updated messaging when start/end is out of province

- src/backend/apps/ferry/serializers.py
- src/backend/apps/ferry/tests/test_ferry_serializer.py
- src/frontend/src/Components/map/panels/FerryPanel.js
- src/frontend/src/Components/map/panels/FerryPanel.scss
- src/frontend/src/Components/shared/FriendlyTime.js
[DBC22-3124](https://moti-imb.atlassian.net/browse/DBC22-3124)
[DBC22-3126](https://moti-imb.atlassian.net/browse/DBC22-3126)
> DBC22-3124: added modified date next to the ferry title

- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-2768
> DBC22-2768: Updates to layer filters' hover state

- src/frontend/src/App.js
DBC22-3132: listed chainups as invisible by default
> DBC22-3132: listed chainups as invisible by default

- src/backend/apps/event/tasks.py
- src/backend/apps/feed/serializers.py
[DBC22-3081](https://moti-imb.atlassian.net/browse/DBC22-3081)
> DBC22-3081: replace timezone with DIT API data

- src/backend/apps/feed/client.py
DBC22-3101: move the hourly forecast group list into the loop for avoiding wrong data
> DBC22-3101: move the hourly forecast group list into the loop for avoiding wrong data

- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/EventsListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3142
> DBC22-3142: Fix for Filter menu title on Delays page

- src/frontend/src/Components/map/layers/index.js
DBC22-3134: enabled chainUps filter layer when using shared URLs
> DBC22-3134: enabled chainUps filter layer when using shared URLs

- src/frontend/src/Components/map/Map.js
https://moti-imb.atlassian.net/browse/DBC22-2622
> DBC22-2622: Updated center camera button on Camera Details page

- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/pages/CameraDetailsPage.js
DBC22-2986: added camera image event handler to cycle through directions
> DBC22-2986: added camera image event handler to cycle through directions

- src/frontend/src/Components/shared/Filters.scss
https://moti-imb.atlassian.net/browse/DBC22-3165
> DBC22-3165: Style update for layer filters

- src/frontend/src/App.scss
- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/pages/AdvisoriesListPage.scss
- src/frontend/src/pages/AdvisoryDetailsPage.js
- src/frontend/src/pages/BulletinDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-2644
> DBC22-2644: Added back button to Advisories and Bulletins detail pages

- src/backend/apps/event/serializers.py
DBC22-3168: set event with weather condition type as road condition display category
> DBC22-3168: set event with weather condition type as road condition display category

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/errors/LocationAccessError.js
- src/frontend/src/Components/map/errors/LocationAccessError.scss
https://moti-imb.atlassian.net/browse/DBC22-2642
> DBC22-2642: Added location permission denied message

- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/CamerasListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-1891
> DBC22-1891: Added a clear button to camera name search

- src/backend/apps/authentication/tests/test_favorite_cameras.py
- src/backend/apps/event/tasks.py
- src/backend/apps/event/tests/test_chain_up_events.py
- src/backend/apps/event/tests/test_data/cars_feed_list_of_chain_ups.json
- src/backend/apps/event/tests/test_data/cars_feed_list_of_five.json
- src/backend/apps/event/tests/test_event_populate.py
- src/backend/apps/event/tests/test_event_serializer.py
- src/backend/apps/feed/client.py
- src/backend/apps/feed/serializers.py
- src/backend/apps/feed/tests/test_event_feed_parse.py
- src/backend/apps/ferry/tests/test_ferry_populate.py
- src/backend/apps/weather/tests/test_current_weather_populate.py
- src/backend/apps/weather/tests/test_data/local_weather_parsed_feed.py
- src/backend/apps/webcam/tests/test_webcam_populate.py
Fixed broken tests, added chain up test, silenced unnecessary log noise.
> DBC22-3131 Fix backend test, add chain up test

- src/frontend/src/Components/shared/PollingComponent.js
[DBC22-3181](https://moti-imb.atlassian.net/browse/DBC22-3181)
> DBC22-3181: prevent polling in the background

- src/frontend/src/Components/events/EventCard.js
- src/frontend/src/Components/events/EventTypeIcon.js
- src/frontend/src/Components/events/EventsTable.js
https://moti-imb.atlassian.net/browse/DBC22-3049
> DBC22-3049: Updated icon for future closure event delays

- src/frontend/src/Components/cameras/CameraCard.js
- src/frontend/src/Components/cameras/CameraCard.scss
Following a conversation with Jason, James and Dave, this change is to show the pill by default for all states (except unavailable), rather than only for the updated state
> DBC22-2999: Show camera update pill by default

- src/frontend/src/pages/CameraDetailsPage.js
Remove this bullet as mentioned during Sprint Review
> DBC22-2997: Camera Details - Remove vandalism from description

- src/frontend/src/Components/map/layers/eventsLayer.js
DBC22-2926: exit the loop when the event was found
> DBC22-2926: exit the loop when the event was found

- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/pages/SavedRoutesPage.scss
- src/frontend/src/styles/bootstrap-customizations.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-2879
> DBC22-2879: Created route email notifications toggle and form

- src/frontend/src/Components/events/EventsTable.js
- src/frontend/src/Components/map/panels/EventPanel.js
DBC22-3194: parse and render the HTML before displaying
> DBC22-3194: parse and render the HTML before displaying

- infrastructure/crunchy-postgres/templates/PostgresCluster.yaml
- infrastructure/crunchy-postgres/values-dev-recovery.yaml
- infrastructure/crunchy-postgres/values-dev.yaml
- infrastructure/crunchy-postgres/values-prod.yaml
- infrastructure/crunchy-postgres/values-uat.yaml
- infrastructure/main/values-dev-recovery.yaml
Added a small change to support doing DB recovery to aid in the Disaster Recovery Process
> DBC22-2470: Improve Disaster Recovery Process

- src/backend/apps/event/enums.py
DBC22-3224: added schedule and start to event diff fields to make sure these fields can be updated
> DBC22-3224: added schedule and start to event diff fields to make sure these fields can be updated

- src/frontend/src/Components/map/Map.js
DBC22-3278: highlight active camera by clicking camera location when camera details loaded
> DBC22-3278: highlight active camera by clicking camera location when camera details loaded

- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Components/shared/Filters.js
DBC22-3204: updated tooltips for commercial vehicles rest stops
> DBC22-3204: updated tooltips for commercial vehicles rest stops

- src/frontend/src/Components/map/Map.js
DBC22-3279: changed zoom level to 9 when camera location button clicked
> DBC22-3279: changed zoom level to 9 when camera location button clicked

- src/frontend/src/pages/AdvisoriesListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3274
> DBC22-3274: Fixed advisories list styling on mobile

- src/frontend/src/pages/VerifyEmailPage.js
https://moti-imb.atlassian.net/browse/DBC22-3275
> DBC22-3275: Fixed email verification copy

- src/backend/apps/authentication/templates/email/email_verification.html
https://moti-imb.atlassian.net/browse/DBC22-3292
> DBC22-3292: Fixed verification email copy

- src/frontend/src/Components/shared/Filters.js
DBC22-3204: minor changes on the tooltip of commercial rest stop layer's filter
> DBC22-3204: minor changes on the tooltip of commercial rest stop layer's filter

- src/frontend/src/Components/map/Map.js
DBC22-3280: set reference feature to clicked when loading camera details page
> DBC22-3280: set reference feature to clicked when loading camera details page

- src/backend/apps/feed/serializers.py
DBC22-3018: used prase id to check if closed
> DBC22-3018: used prase id to check if closed

- src/frontend/src/Components/cameras/CameraCard.scss
https://moti-imb.atlassian.net/browse/DBC22-3317
> DBC22-3317: Added padding for focus ring on camera cards

- src/frontend/src/pages/CameraDetailsPage.scss
…lay the day
DBC22-3328: fixed the issue that control button not showing up on replay the day
> DBC22-3328: fixed the issue that control button not showing

- src/frontend/src/Components/routing/RouteSearch.scss
- src/frontend/src/pages/ContainerSidePanel.scss
https://moti-imb.atlassian.net/browse/DBC22-3172
> DBC22-3172: Fixed focus highlight on location inputs

- src/frontend/src/Modal.js
DBC22-3340: avoided tooltip button click event to be triggered
> DBC22-3340: avoided tooltip button click event to be triggered

- src/frontend/src/pages/CameraDetailsPage.js
DBC22-3315: set camera when it's not been set yet
> DBC22-3315: set camera when it's not been set yet

- src/frontend/src/Components/routing/RouteDetails.js
DBC22-3314: save route when selected route is the current route
> DBC22-3314: save route when selected route is the current route

- src/frontend/src/Components/routing/forms/NotificaitonDateTime.scss
- src/frontend/src/Components/routing/forms/NotificationDateTime.js
[DBC22-3365](https://moti-imb.atlassian.net/browse/DBC22-3365)
> DBC22-3365: tz note for time settings

- src/frontend/src/App.scss
- src/frontend/src/Components/cameras/CameraList.scss
- src/frontend/src/Components/shared/HighwayFilter.js
- src/frontend/src/Components/shared/HighwayFilter.scss
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/pages/ContainerSidePanel.scss
https://moti-imb.atlassian.net/browse/DBC22-2859
High-level changes from this enhancement ticket for the drop-down filters on the Cameras page:
- Minor styling changes to the dropdown filters and camera search input field
- On tablet/mobile, Search by camera name  now shows/hides input field below the tools container
- On desktop, the Highway filters button now displays the selected highway number
- On tablet/mobile, the Highway filters button has an active state and the selected highway number is displayed below the tools container with wording: "Filtering by:..."
- On mobile, the Highway filters button now triggers an overlay to display the highway filter options.
> Feature/DBC22-2859: Improve usability of drop-down filters

- src/frontend/src/Components/routing/RouteDetails.scss
https://moti-imb.atlassian.net/browse/DBC22-3384
> DBC22-3384: Style update to route disclosure pills

- src/frontend/src/Components/routing/forms/NotificaitonDateTime.scss
- src/frontend/src/Components/routing/forms/NotificationDateTime.js
[DBC22-3366
](https://moti-imb.atlassian.net/browse/DBC22-3366)
I opted to add a checkbox for all-day option as it is very difficult to customize options in this external package.
As well, steps below 15 minutes will result in the overlay not showing at all.
> DBC22-3366: all day option

- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/Header.scss
https://moti-imb.atlassian.net/browse/DBC22-3342
> Feature/DBC22-3342: Added report a problem link to header

- src/frontend/src/Components/routing/forms/NotificationDateTime.js
[DBC22-3414](https://moti-imb.atlassian.net/browse/DBC22-3414)
> DBC22-3414: fixed toISOString not taking timezone into account

- src/frontend/src/Components/shared/Filters.scss
https://moti-imb.atlassian.net/browse/DBC22-1784
> DBC22-1784: Fix for Filters overlay overlap with nav header

- src/frontend/src/styles/bootstrap-customizations.scss
[DBC22-3406](https://moti-imb.atlassian.net/browse/DBC22-3406)
> DBC22-3406: workaround styling for firefox css bug

- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/EventsListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3410
> DBC22-3410: Applied style changes to dropdown filters on Delays page

- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3435
> DBC22-3435: Fix for Layer filter button's active state on Camera Details page

- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3441
> DBC22-3441: Updated camera image update notice

- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/Components/bulletins/BulletinsList.js
- src/frontend/src/pages/AdvisoriesListPage.js
- src/frontend/src/pages/AdvisoryDetailsPage.js
- src/frontend/src/pages/AdvisoryDetailsPage.scss
- src/frontend/src/pages/BulletinDetailsPage.js
- src/frontend/src/pages/BulletinsListPage.js
DBC22-2876: added loading states for CMS list page
> DBC22-2876: added loading states for CMS list page

- src/frontend/src/Components/routing/RouteDetails.scss
https://moti-imb.atlassian.net/browse/DBC22-3412
> DBC22-3412: Fixed position for route notifications modal's buttons

- infrastructure/crunchy-postgres/templates/PostgresCluster.yaml
- infrastructure/crunchy-postgres/values-dev-pg17-recovery.yaml
- infrastructure/crunchy-postgres/values-dev-pg17-standby.yaml
- infrastructure/crunchy-postgres/values-dev-pg17.yaml
- infrastructure/crunchy-postgres/values-prod-pg17.yaml
- infrastructure/crunchy-postgres/values-test-pg17.yaml
- infrastructure/crunchy-postgres/values-uat-pg17.yaml
- infrastructure/main/values-prod.yaml
- infrastructure/main/values-uat.yaml
Had to rebuild the DB's to upgrade from pg15 to pg17
> DBC22-2921: Updated crunchy helm charts

- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/pages/AccountPage.scss
- src/frontend/src/styles/bootstrap-customizations.scss
https://moti-imb.atlassian.net/browse/DBC22-3466
> DBC22-3466: Fix styling for deactivate account modal

- src/frontend/src/Components/routing/RouteDetails.scss
https://moti-imb.atlassian.net/browse/DBC22-3412
> DBC22-3412: Fixed position of controls for route notification settings

- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/Filters.scss
- src/frontend/src/Footer.js
- src/frontend/src/Footer.scss
https://moti-imb.atlassian.net/browse/DBC22-3506
> DBC22-3506: Added seasonal load restrictions link

- src/backend/apps/event/helpers.py
- src/backend/apps/event/tasks.py
- src/backend/apps/event/templates/email/event_updated.html
- src/frontend/src/App.js
- src/frontend/src/Components/data/routes.js
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/MapWrapper.js
- src/frontend/src/Components/map/dataLoaders/advisories.js
- src/frontend/src/Components/map/dataLoaders/cameras.js
- src/frontend/src/Components/map/dataLoaders/currentWeathers.js
- src/frontend/src/Components/map/dataLoaders/events.js
- src/frontend/src/Components/map/dataLoaders/ferries.js
- src/frontend/src/Components/map/dataLoaders/hef.js
- src/frontend/src/Components/map/dataLoaders/regionalWeathers.js
- src/frontend/src/Components/map/dataLoaders/restStops.js
- src/frontend/src/Components/map/helpers/index.js
- src/frontend/src/Components/map/helpers/spatial.js
- src/frontend/src/Components/map/layers/routeLayer.js
- src/frontend/src/Components/routing/DistanceLabels.js
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteSearch.js
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/MapPage.js
- src/frontend/src/slices/cmsSlice.js
- src/frontend/src/slices/feedsSlice.js
- src/frontend/src/slices/index.js
- src/frontend/src/slices/routesSlice.js
[DBC22-3396](https://moti-imb.atlassian.net/browse/DBC22-3396)
I will create a meeting to review this and other outstanding PRs on Monday.
> DBC22-3396: route population from email notifications, various fixes on data loading

- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/Components/map/panels/CamPanel.scss
https://moti-imb.atlassian.net/browse/DBC22-3405
> DBC22-3405: Added camera details page link to map sidepanel

- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3535
> DBC22-3535: Fixed styling for stale and delayed camera image notifications.

- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3428
> DBC22-3428: Tightening spacing on mobile UI for Delays page

- src/frontend/src/Components/map/panels/CamPanel.js
- src/frontend/src/Components/map/panels/CamPanel.scss
Added click on camera image on the camera side panel.
> DBC22-3405: Added camera clear CTA

- src/frontend/src/Components/data/featureStyleDefinitions.js
- src/frontend/src/Components/map/helpers/events.js
[DBC22-3372](https://moti-imb.atlassian.net/browse/DBC22-3372)
> DBC22-3372: future closure icons

- src/frontend/src/Components/routing/RouteDetails.scss
https://moti-imb.atlassian.net/browse/DBC22-3487 and https://moti-imb.atlassian.net/browse/DBC22-3488
> DBC22-3487: Fixing notification settings screen on iOS

- src/frontend/src/Components/map/panels/BorderCrossingPanel.scss
- src/frontend/src/Components/shared/ShareURLButton.scss
https://moti-imb.atlassian.net/browse/DBC22-3616
> DBC22-3616: aesthetic fixes per request

- src/frontend/src/Components/map/MapWrapper.js
- src/frontend/src/Components/map/helpers/spatial.js
[DBC22-3626](https://moti-imb.atlassian.net/browse/DBC22-3626)
> DBC22-3626: route filtering optimization

- src/frontend/src/pages/ProblemsPage.js
- src/frontend/src/pages/ProblemsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3638
> Remove Report Downed Power Line section from Report a Problem

- src/frontend/src/Components/map/handlers/click.js
…e map
DBC22-3670: added default behavior when not clicked on features of the map
> DBC22-3670: added default behavior when not clicked on features of the map

- src/frontend/src/Components/routing/forms/NotificationDateTime.js
DBC22-3500: to prevent default start date becomes null when the page initially loaded
> DBC22-3500: to prevent default start date becomes null when the page initially loaded

- src/frontend/src/Components/map/MapWrapper.js
[DBC22-3682](https://moti-imb.atlassian.net/browse/DBC22-3682)
> DBC22-3682: map layers no longer update when not on

- src/backend/apps/event/enums.py
- src/backend/apps/feed/serializers.py
DBC22-3606: check closure for event category of incident
> DBC22-3606: check closure for event category of incident

- src/frontend/src/Components/shared/Filters.js
[DBC22-3521](https://moti-imb.atlassian.net/browse/DBC22-3521)
> DBC22-3521: Turn-on relevant layers when a route is selected

- .github/workflows/standbycheck.yml
- .github/workflows/trivyscans.yml
- compose/standbycheck/Dockerfile
- compose/standbycheck/app/Caddyfile_200
- compose/standbycheck/app/Caddyfile_503
- compose/standbycheck/app/lbcheck.sh
- compose/standbycheck/start.sh
- infrastructure/standbycheck/Chart.yaml
- infrastructure/standbycheck/README.md
- infrastructure/standbycheck/templates/_helpers.tpl
- infrastructure/standbycheck/templates/deployment.yaml
- infrastructure/standbycheck/templates/gold-secret.yaml
- infrastructure/standbycheck/templates/networkpolicy.yaml
- infrastructure/standbycheck/templates/pdb.yaml
- infrastructure/standbycheck/templates/route.yaml
- infrastructure/standbycheck/templates/sa.yaml
- infrastructure/standbycheck/templates/sa_role.yaml
- infrastructure/standbycheck/templates/sa_rolebinding.yaml
- infrastructure/standbycheck/templates/sa_secret.yaml
- infrastructure/standbycheck/templates/service.yaml
- infrastructure/standbycheck/values-dev-dr.yaml
- infrastructure/standbycheck/values-dev.yaml
- infrastructure/standbycheck/values-prod-dr.yaml
- infrastructure/standbycheck/values-prod.yaml
- infrastructure/standbycheck/values-test-dr.yaml
- infrastructure/standbycheck/values-test.yaml
- infrastructure/standbycheck/values-uat-dr.yaml
- infrastructure/standbycheck/values-uat.yaml
https://moti-imb.atlassian.net/browse/DBC22-3599
This is the code required for the pods that the GSLB monitors to see if the cluster is up.
This is deployed separately from the rest of the site as this code almost never changes and if anything happens to this, traffic will failover to golddr inadvertently.
> DBC22-3599: Add Standbycheck

- src/frontend/src/Components/map/layers/camerasLayer.js
- src/frontend/src/Components/map/layers/currentWeatherLayer.js
- src/frontend/src/Components/map/layers/ferriesLayer.js
- src/frontend/src/Components/map/layers/hefLayer.js
- src/frontend/src/Components/map/layers/largeRestStopsLayer.js
- src/frontend/src/Components/map/layers/regionalWeatherLayer.js
- src/frontend/src/Components/map/layers/restStopsLayer.js
DBC22-3719: kept feature icons highlighted during dynamic updates
> DBC22-3719: kept feature icons highlighted during dynamic updates

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/layers/routeLayer.js
DBC22-3796: checked if route exists otherwise return to avoid errors
> DBC22-3796: checked if route exists otherwise return to avoid errors

- src/frontend/src/pages/CameraDetailsPage.js
DBC22-3822: pause the replay when switching cameras
> DBC22-3822: pause the replay when switching cameras

- src/backend/apps/cms/templates/email/advisory_updated.html
- src/frontend/src/App.scss
- src/frontend/src/Components/data/featureStyleDefinitions.js
- src/frontend/src/Components/map/panels/AdvisoriesPanel.scss
- src/frontend/src/pages/AdvisoriesListPage.scss
- src/frontend/src/pages/AdvisoryDetailsPage.scss
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-3639
> DBC22-3639: Updated advisories styles throughout whole site

- src/frontend/src/pages/BulletinDetailsPage.js
This seems to fix the looping issue on the bulletins page. Tested in dev and confirmed it no longer loops
> DBC22-3437: Fix for bulletin loop

- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/panels/RouteDetailsPanel.js
- src/frontend/src/Components/map/panels/RouteDetailsPanel.scss
- src/frontend/src/Components/routing/DistanceLabels.js
- src/frontend/src/Components/routing/DistanceLabels.scss
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/Components/shared/Filters.scss
https://moti-imb.atlassian.net/browse/DBC22-3750
> Feature/DBC22-3750: Updating selected alternate route

- src/frontend/src/Components/report/ReportMap.scss
- src/frontend/src/pages/ReportRoadPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3536
> DBC22-3536: Fix for RAHP map buttons

- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/routing/RouteMap.scss
https://moti-imb.atlassian.net/browse/DBC22-3875
> DBC22-3875: Removed unused element creating empty scrollable space

- src/frontend/src/Components/map/layers/borderCrossingsLayer.js
- src/frontend/src/Components/map/layers/index.js
- src/frontend/src/Components/map/panels/BorderCrossingPanel.js
DBC22-3663: set reference feature for border crossings to avoid focus lost when refresh
> DBC22-3663: set reference feature for border crossings to avoid focus lost when refresh

- src/frontend/src/Components/shared/Filters.js
DBC22-3835: close side panel when filter layers get disabled
> DBC22-3835: close side panel when filter layers get disabled

- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-3844
> DBC22-3844: Fixed notification banner on camera details

- src/frontend/src/pages/CamerasListPage.js
DBC22-3853: set default value for AsyncTypeahead when window resizing
> DBC22-3853: set default value for AsyncTypeahead when window resizing

- .github/workflows/standbycheck.yml
- compose/standbycheck/Dockerfile
- compose/standbycheck/app/lbcheck.sh
Use curl instead of oc to do the standbycheck. Looks to use about 20% of the CPU usage that the oc tool does.
> DBC22-3890: Reduce Standbycheck CPU usage

- src/frontend/src/Components/advisories/AdvisoriesList.js
- src/frontend/src/Components/advisories/AdvisoriesList.scss
- src/frontend/src/Components/data/featureStyleDefinitions.js
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/handlers/click.js
- src/frontend/src/Components/map/handlers/hover.js
- src/frontend/src/Components/map/layers/advisoriesLayer.js
- src/frontend/src/Components/map/panels/index.js
- src/frontend/src/styles/variables.scss
[DBC22-3756](https://moti-imb.atlassian.net/browse/DBC22-3756)
> DBC22-3756: map advisory rework

- src/frontend/src/Components/map/filter/FilterTabs.scss
https://moti-imb.atlassian.net/browse/DBC22-3931
> DBC22-3931: Fixed map layers panel height

- src/frontend/src/App.js
- src/frontend/src/App.scss
- src/frontend/src/Components/cameras/CameraList.scss
- src/frontend/src/Components/events/EventsTable.scss
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/filter/MapFilters.scss
- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/Components/shared/header/UserNavigation.scss
- src/frontend/src/pages/BulletinsListPage.js
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/CamerasListPage.scss
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.js
- src/frontend/src/pages/EventsListPage.scss
- src/frontend/src/pages/MapPage.js
https://moti-imb.atlassian.net/browse/DBC22-3878
Currently still working on tracking the header height globally to set/change absolute positions accordingly.
> DBC22-3878: Updated header and filter groups in Cameras page and Delays page.

- src/frontend/src/Components/map/helpers/spatial.js
- src/frontend/src/Components/map/panels/RouteDetailsPanel.js
- src/frontend/src/Components/routing/RouteDetails.js
- src/frontend/src/Components/routing/RouteDetails.scss
- src/frontend/src/Components/routing/RouteObjectList.js
- src/frontend/src/Components/routing/RouteObjectList.scss
- src/frontend/src/styles/variables.scss
[DBC22-3632](https://moti-imb.atlassian.net/browse/DBC22-3632)
> DBC22-3632: object list component for routes

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/filter/FilterTabs.js
- src/frontend/src/Components/map/filter/FilterTabs.scss
- src/frontend/src/Components/routing/RouteSearch.scss
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/pages/MapPage.js
for 3878: https://moti-imb.atlassian.net/browse/DBC22-3878
and 3933: https://moti-imb.atlassian.net/browse/DBC22-3933
> DBC22-3878: Fixed header margins

- src/frontend/src/Components/routing/forms/NotificationEventType.js
DBC22-3823: added missing checked status for chainups
> DBC22-3823: added missing checked status for chainups

- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-3921
> DBC22-3921: Fix for overflow on delayed camera notifications

- compose/frontend/default.conf
- compose/openshiftjobs/scripts/analyzeexportlogs.sh
- infrastructure/crunchy-postgres/values-dev.yaml
- infrastructure/crunchy-postgres/values-prod.yaml
- infrastructure/crunchy-postgres/values-test.yaml
- infrastructure/crunchy-postgres/values-uat.yaml
- infrastructure/main/values-dev.yaml
- infrastructure/main/values-prod.yaml
- infrastructure/main/values-test.yaml
- infrastructure/main/values-uat.yaml
- infrastructure/syncthing/README.md
- infrastructure/syncthing/values-dev.yaml
- infrastructure/syncthing/values-prod.yaml
- infrastructure/syncthing/values-test.yaml
- infrastructure/syncthing/values-uat.yaml
Just a few changes to improve resource allocation for various site components
> DBC22-3859: Resource improvements

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/filter/FilterTabs.js
- src/frontend/src/Components/map/filter/FilterTabs.scss
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/pages/MapPage.js
https://moti-imb.atlassian.net/browse/DBC22-3972 and https://moti-imb.atlassian.net/browse/DBC22-3966
> DBC22- 3972: Adding media queries for tablet size

- src/frontend/src/Components/map/filter/FilterTabs.scss
https://moti-imb.atlassian.net/browse/DBC22-3972
> DBC22-3972: Added padding for the legend tab

- src/frontend/src/App.scss
- src/frontend/src/pages/CameraDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.scss
- src/frontend/src/styles/bootstrap-customizations.scss
https://moti-imb.atlassian.net/browse/DBC22-3526
> DBC22-3526: Update on camera details controls

- src/frontend/src/App.scss
https://moti-imb.atlassian.net/browse/DBC22-4005
> DBC22-4005: Fixed embedded content overlapping in bulletins

- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/pages/CameraDetailsPage.js
https://moti-imb.atlassian.net/browse/DBC22-4057
> DBC22-4057: Added missing updated banner on camera details

- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/ContainerSidePanel.scss
for https://moti-imb.atlassian.net/browse/DBC22-3915 and https://moti-imb.atlassian.net/browse/DBC22-3913
> DBC22-3915: Fix for camera name search on camera list page

- src/frontend/src/Components/shared/header/Header.scss
https://moti-imb.atlassian.net/browse/DBC22-3999
Wasn't able to reproduce the bug, so discussed with Jason to give this a try and test on his older physical device (iphone 12).
> DBC22-3999: Added padding to the last hamburger nav item.

- src/frontend/src/Components/map/filter/FilterTabs.scss
https://moti-imb.atlassian.net/browse/DBC22-3920
> DBC22-3920: Crop extra blank space on layer filters on map

- src/frontend/src/Components/map/filter/FilterTabs.scss
https://moti-imb.atlassian.net/browse/DBC22-4028
> DBC22-4028: Fixed layers menu height to bottom of header on mobile

- src/frontend/src/pages/EventsListPage.scss
https://moti-imb.atlassian.net/browse/DBC22-4106
> DBC22-4106: Fix layer filters height on delays page

- src/frontend/src/Components/report/ReportMap.js
- src/frontend/src/Components/report/ReportMap.scss
https://moti-imb.atlassian.net/browse/DBC22-4081
> DBC22-4081: Adjusting RAHP map for mobile landscape

- src/backend/apps/event/helpers.py
- src/backend/apps/event/tests/test_event_populate.py
[DBC22-2259](https://moti-imb.atlassian.net/browse/DBC22-2259)
Please close after verification.
> DBC22-2259: added tests for display category

- src/frontend/src/Components/map/Map.scss
https://moti-imb.atlassian.net/browse/DBC22-4111
> DBC22-4111: Camera details page side panel fixed width

- src/frontend/src/Components/shared/Filters.js
Variation on prior race condition.
> DBC22-4131 Delay events not toggling with filter

- src/frontend/src/Components/routing/RouteSearch.scss
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/pages/ContainerSidePanel.scss
https://moti-imb.atlassian.net/browse/DBC22-4107
> DBC22-4107: displaying route component on narrow desktop browser width sizes

- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4020
> DBC22-4020: Made list filter bar sticky on desktop

- infrastructure/syncthing/templates/networkpolicy.yaml
- infrastructure/syncthing/templates/route.yaml
https://moti-imb.atlassian.net/browse/DBC22-4169
> DBC22-4169: Update Syncthing ipallowlist

- src/frontend/src/App.scss
- src/frontend/src/pages/CamerasListPage.js
for https://moti-imb.atlassian.net/browse/DBC22-4145
> DBC22-4145: Adjusted height of overlay depending on header height

- src/frontend/src/Components/map/Map.scss
https://moti-imb.atlassian.net/browse/DBC22-4179
> DBC22-4179: Removed min-width for side-panels on mobile

- src/frontend/src/App.scss
- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/EventsListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4193
> DBC22-4193: Updating advisories mobile panel's height on open

- src/frontend/src/pages/CamerasListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4145
> DBC22-4145: Fix for highway mobile panel's height on camera list

- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/Header.scss
- src/frontend/src/Components/shared/header/UserNavigation.scss
https://moti-imb.atlassian.net/browse/DBC22-4172
> DBC22-4172: Updated header breakpoints and spacing

- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/EventsListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4218
> DBC22-4218: Swapping out 100vh for 100% for advisories panels

- src/frontend/src/Components/map/panels/BorderCrossingPanel.scss
- src/frontend/src/Components/map/panels/EventPanel.scss
- src/frontend/src/Components/map/panels/FerryPanel.scss
- src/frontend/src/Components/map/panels/index.scss
- src/frontend/src/Components/shared/ShareURLButton.scss
- src/frontend/src/styles/variables.scss
Sidepanel fixes:
- Ferries type size adjustment
- Chainups theming
- Border crossing spacing
> Update color and spacing

- src/frontend/src/Components/shared/Survey.js
- src/frontend/src/Components/shared/Survey.scss
Updated background for error message on popup survey
> Low contrast error message on survey

- src/frontend/src/Components/advisories/AdvisoriesList.scss
- src/frontend/src/Components/map/panels/AdvisoriesPanel.scss
- src/frontend/src/pages/AdvisoryDetailsPage.scss
- fixes button width in sidepanels (map and cam/delay pages)
- fixes timestamp spacing in panels + details
> fix advisories related visual bugs

- src/frontend/src/Components/shared/header/UserNavigation.scss
https://moti-imb.atlassian.net/browse/DBC22-4171
> DBC22-4171: Change to auto for scroll on user navigation

- src/frontend/src/App.scss
- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/Map.scss
- src/frontend/src/Components/map/errors/LocationAccessError.js
- src/frontend/src/Components/map/errors/LocationAccessError.scss
- src/frontend/src/Components/map/errors/NetworkError.js
- src/frontend/src/Components/map/errors/NetworkError.scss
- src/frontend/src/Components/map/errors/ServerError.js
- src/frontend/src/Components/map/errors/ServerError.scss
- src/frontend/src/Components/map/errors/StaleLinkError.js
- src/frontend/src/Components/routing/RouteSearch.scss
- src/frontend/src/styles/variables.scss
https://moti-imb.atlassian.net/browse/DBC22-4220
> DBC22-4220: Updated system notifications

- src/frontend/src/Components/shared/header/Header.js
https://moti-imb.atlassian.net/browse/DBC22-4039
> DBC22-4039: Hiding route search component when hamburger is open

- src/frontend/src/pages/CamerasListPage.js
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4237
> DBC22-4237: Updated handle scroll to use IntersectionObserver for style changes on sticky filters

- src/frontend/src/App.scss
- src/frontend/src/Components/map/filter/FilterTabs.scss
- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/pages/ContainerSidePanel.scss
- src/frontend/src/pages/EventsListPage.js
https://moti-imb.atlassian.net/browse/DBC22-4559
> DBC22-4559: Map layers height fixed to leave space for zoom buttons

- src/frontend/src/Components/map/filter/FilterTabs.scss
https://moti-imb.atlassian.net/browse/DBC22-4618
> DBC22-4618: Fix for Map layers overflow scroll

- src/frontend/src/Components/map/Map.scss
https://moti-imb.atlassian.net/browse/DBC22-4563
> DBC22-4563: Roll-back to removing transition animation to fix floating buttons.

- src/frontend/src/App.scss
- src/frontend/src/Components/map/filter/MapFilters.js
- src/frontend/src/Components/map/panels/BorderCrossingPanel.js
- src/frontend/src/Components/map/panels/CoastalFerryPanel.js
- src/frontend/src/Components/map/panels/EventPanel.js
- src/frontend/src/Components/map/panels/FerryPanel.js
- src/frontend/src/Components/map/panels/RestStopPanel.js
- src/frontend/src/Components/map/panels/WildfirePanel.js
- src/frontend/src/Components/map/panels/weather/HefPanel.js
- src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.js
- src/frontend/src/Components/report/ReportMap.js
- src/frontend/src/Components/shared/Filters.js
- src/frontend/src/Components/shared/SocialSharing.js
- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Footer.js
https://moti-imb.atlassian.net/browse/DBC22-4318
> DBC22-4318: Removed external links opening in a new tab

- src/frontend/src/Components/shared/header/UserNavigation.js
- src/frontend/src/pages/AdvisoryDetailsPage.js
- src/frontend/src/pages/BulletinDetailsPage.js
- src/frontend/src/pages/CameraDetailsPage.js
https://moti-imb.atlassian.net/browse/DBC22-4299
> DBC22-4299: Added focus on back to last page buttons

- src/frontend/src/Components/shared/header/Header.js
- src/frontend/src/Components/shared/header/UserNavigation.js
- src/frontend/src/Modal.js
https://moti-imb.atlassian.net/browse/DBC22-4303
Alternative solution without using a library.
> DBC22-4303: Locking focus inside sign in modal

- src/frontend/src/Components/map/Map.js
- src/frontend/src/Components/map/filter/FilterTabs.scss
- src/frontend/src/Components/map/filter/MapFilters.scss
- src/frontend/src/pages/CameraDetailsPage.scss
https://moti-imb.atlassian.net/browse/DBC22-4713
> DBC22-4713: Adding legend tab to filters on Camera details page minimap.

- src/frontend/src/Components/cameras/directions/CameraOrientations.js
- src/frontend/src/Components/cameras/directions/CameraOrientations.scss
- src/frontend/src/Components/cameras/directions/CameraThumbnail.js
- src/frontend/src/Components/cameras/directions/CameraThumbnail.scss
https://moti-imb.atlassian.net/browse/DBC22-4857
> DBC22-4857: Added states to camera thumbnails

- src/frontend/src/Components/cameras/directions/CameraThumbnail.scss
https://moti-imb.atlassian.net/browse/DBC22-4906
> DBC22-4906: Added styling for updated pill on camera thumbnail.
