.gitlint, .pre-commit-config.yaml, README.md
These configurations reflect the settings used for the code challenge. The additions on lines 21 and 22 of the .gitlint file remove the requirement for a body message in commits. Please let me know if a body message should be required when composing commit messages.
=> DBC22-255: added pre-commit config and gitlint

src/frontend/src/Components/Map.js
Currently the pin logic is held inside the Map.js file mirroring the existing MyLocation pin logic, due to the fact that the markup needs to be directly injected into the Openlayers map. Alternate or more maintainable alternatives are welcome.
=> DBC22-911: Location search pin logic

src/frontend/src/Components/Map.js, src/frontend/src/Components/Map.scss
Removed mobile layout style settings for overriding openlayer dynamic style. These block has no effect on the mobile layout but impacts the my location pin point displaying.
=> DBC22-931: Removed overriding openlayer dynamic styles for mobile layout

src/frontend/src/Components/Map.js, src/frontend/src/Components/map/mapPopup.js
DBC22-1219: use popup ref when icon clicked to prevent popup onClick event got triggered.
=> DBC22-1219: use popup ref when icon clicked

src/backend/apps/cms/serializers.py
In OpenShift environments, this essentially just removes the host from the image url. This should work because the FE and BE share the same base URL.
In your local environment however, you may need to add the DJANGO_URL env variable to not have images going to the wrong port (localhost:3000 instead of localhost:8000).
=> DBC22-1703: fixed image paths for cms models

compose/frontend/default.conf, infrastructure/_django/templates/django-route.yaml, infrastructure/main/values-prod.yaml, infrastructure/main/values-test.yaml, infrastructure/main/values-uat.yaml
Updating some resource values at same time to ensure capacity.
=> DBC22-1788: Cache Django Media

src/frontend/src/Components/map/mapPopup.js, src/frontend/src/Components/map/mapPopup.scss, src/frontend/src/styles/variables.scss
Similar to the road weather sidepanel DBC22-1732, worked ahead with styling the sidepanel for regional weather with dummy data.
This branch is based off of the branch for the road weather sidepanel feature/DBC22-1732, so either merge in only this branch to have both, or please rebase and merge this one after that one.
The html structure to use for the regional weather sidepanel can be found commented out in Map.js file under the block with class name "popup--regional-weather".
=> DBC22-1486: Added styling and html structure for regional weather sidepanel

src/backend/.pylintrc, src/backend/requirements/development.txt
Recreated this PR from https://github.com/bcgov/DriveBC.ca/pull/109.
This PR added backend linting capability by applying pylint on python code.
Please configure the dev IDE to enable pylint on VS Code or PyCharm.
How to Install Pylint in PyCharm:
pip install pylint
use "which pylint" (for mac) or "where pylint" (for windows) to get the Pylint installation path.
navigate to File->Settings->External tools.
Enter the installation path of pylint in the field 'Program', enter data for all other fields as desired, i.e., Arguments: the .pylintrc file path in the backend python code, Working directory: to the backend python code root directory.
right clicke on the python file, select Open in-> Terminal
Run command 'pylint fileName.py'
The .pylintrc file is generated by using command "pylint …
=> DBC22-783: backend linting setup

src/frontend/src/Components/advisories/AdvisoriesList.scss, src/frontend/src/Components/advisories/EmptyAdvisory.js, src/frontend/src/Components/bulletins/BulletinsList.scss, src/frontend/src/Components/bulletins/EmptyBulletin.js
This branch contains both DBC22-1882 and DBC22-1883.
=> DBC22-1883

src/frontend/src/Components/Map.js, src/frontend/src/Components/RestStopTypeIcon.js, src/frontend/src/Components/data/featureStyleDefinitions.js, src/frontend/src/Components/data/restStops.js, src/frontend/src/Components/map/layers/restStopsLayer.js, src/frontend/src/Components/map/mapPopup.js
DBC22-1885: resolved conflicts and made icons consistent
=> DBC22-1885: resolved conflicts and made icons consistent

compose/openshiftjobs/scripts/analyzeexportlogs.sh
Using x-forwarded-for in the nginx log, but it can contain multiple IP's in the case where the traffic gets proxied. This log format change ensures we only look at the first IP (which is the client IP)
=> DBC22-2262: Update goaccess log format

src/backend/apps/cms/models.py
DBC22-1139: added non-editable metadata fields for Advisory, Bulletin and Ferry
=> DBC22-1139: added non-editable metadata fields for Advisory, Bulletin and Ferry

compose/openshiftjobs/scripts/analyzeexportlogs.sh
Due to a sysdig change, it looks like it broke goaccess log analyzing by causing access log entries like this:
`- - - [21/Jun/2024:06:49:57 +0000] "GET /nginx_status/ HTTP/1.1" 200 594 "-" "Sysdig Agent/1.0" - "text/html" 0.000 `
Goaccess requires a host IP which this doesn't have, which was causing the jobs to fail.
This fix will need to go to all environments sooner than later
=> DBC22-2350: Filter out invalid access log lines

src/frontend/src/Components/advisories/AdvisoriesOnMap.js, src/frontend/src/Components/map/Map.js, src/frontend/src/Components/map/panels/AdvisoriesPanel.js
[DBC22-2249](https://jira.th.gov.bc.ca/browse/DBC22-2249)
@minORC this bug was a result of us trying to work around the mobile advisories bug where the advisories popup panel eats up the map viewport which could result in a blank panel.
To solve this, we are now using advisoriesInView everywhere, but in AdvisoriesPanel we are no longer directly displaying advisories from the prop; we're mapping to a state and intentionally _not_ using a useEffect call to update it. Essentially this "snapshots" the panel display to what was showing on the map at the time of the click.
=> DBC22-2249: fixed advisories in view behavior for side panel

compose/openshiftjobs/DockerFile
With this update I can remove a workaround to get the version of goaccess I needed working.
=> DBC22-2421: Update Alpine Image for OpenShiftJobs

compose/openshiftjobs/scripts/analyzeexportlogs.sh, compose/openshiftjobs/scripts/ziplogs.sh
https://jira.th.gov.bc.ca/browse/DBC22-2448
There is a scenario where the pod name can have a 10 digit # in it which breaks the grep logic used to find the timestamp in the logfile. This update addresses that by looking for -access.log after the timestamp. Alpine didn't seem to support grep lookahead so using sed instead
=> DBC22-2448: Improved logic to identify timestamps

src/backend/apps/feed/tasks.py
https://jira.th.gov.bc.ca/browse/DBC22-2383
As discussed we were seeing an issue where weather data didn't match what environment canada was displaying, so this increases the frequency of pulling data from SAWSx to every 10 min instead of 20 min. Also updated frequency for moti weather data.
=> DBC22-2383: Increase frequency of weather updates

src/frontend/src/Components/data/locations.js
https://jira.th.gov.bc.ca/browse/DBC22-1722
Updating the parameters for querying the geocoder to more closely match what is used on the geocoder demo page here: https://bcgov.github.io/ols-devkit/ols-demo/index.html
Changes include
- Minscore now 50 instead of 65 which means you should see results as early as you enter your first 3 characters (prior to this it would often take 6+ characters) 
- maxResults now 7 instead of 20. The demo page had 5, but in consultation with Chris and James we settled on 7 for DriveBC. 
- locationDescriptor is a new parameter. Demo page had parcelPoint, but in reading the documentation, routingPoint is more appropriate "A point lying on a road centreline and directly in front of a site's accessPoint. A routing point is intended for use by routing algorithms …
=> DBC22-1722:Update geocoder parameters

src/frontend/src/Components/map/Map.js, src/frontend/src/Components/map/layers/camerasLayer.js, src/frontend/src/Components/map/layers/currentWeatherLayer.js, src/frontend/src/Components/map/layers/eventsLayer.js, src/frontend/src/Components/map/layers/ferriesLayer.js, src/frontend/src/Components/map/layers/index.js, src/frontend/src/Components/map/layers/largeRestStopsLayer.js, src/frontend/src/Components/map/layers/regionalWeatherLayer.js, src/frontend/src/Components/map/layers/restStopsLayer.js, src/frontend/src/Components/shared/Filters.js
[DBC22-2509](https://jira.th.gov.bc.ca/browse/DBC22-2509)
Simple logic despite changes in a lot of files. Key highlights:
- loadingLayers state is initialized from mapContext.visible_layers; the spinner will only be visible if the layer is enabled on load. 
- The loading function of each layers calls setState for this and sets their relative loading state to false. For styling, comment out these lines to never hide the spinner. e.g. 
`
setLoadingLayers(prevState => ({
...prevState,
cameras: false
}));
`
- events, weathers and restStops have shared layers
=> DBC22-2509: filters loading states in maps

src/frontend/src/Components/data/locations.js
https://jira.th.gov.bc.ca/browse/DBC22-1321
This adds a new query parameter called exactSpelling which fixes a lot of issues we had with the geocoder. Currently only works in their test environments, but I've pointed our dev environment there for testing.
Change is backwards compatible, meaning we can use this new parameter and it will not break when using the current prod URL.
They are completing their testing cycle on Tues Aug 27th and will move it to prod thereafter.
=> DBC22-1321: Add new parameter to Geocoder query

src/frontend/src/Components/map/Map.js, src/frontend/src/Components/map/MapWrapper.js
This PR fixed the issue that AdvisoriesWidget does not showing up when the map refreshed. 
The fix will fetch advisories when map the is initial loaded.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-1980
=> DBC22-1980: fetch advisories when map initial loading

src/frontend/src/Components/events/EventCard.js, src/frontend/src/Components/events/EventCard.scss, src/frontend/src/pages/EventsListPage.js, src/frontend/src/pages/EventsListPage.scss
Changed click action in Event cards on mobile as the design changed.
Used to be the whole event card being clickable, to now, the design has added an explicit link to "View on map" so the click action has been moved accordingly to that button/link.
=> DBC22-2613: Changed click action in Event cards on mobile

compose/frontend/default.conf, compose/frontend/entrypoint
https://jira.th.gov.bc.ca/browse/DBC22-2667
I added the header on default.conf and then in entrypoint file I remove it for the prod environment. I did the script in on my PC to confirm it does indeed remove the line for prod.
Once merged and deployed to test we can have Google re-scan the dev/test sites
=> DBC22-2667: Add noindex header for non-prod

src/frontend/src/Components/cameras/CameraList.js
DBC22-2592: fixed highway filter does not show non highway cameras
The root cause of this issue is the filter filtering out highway based on the camera "highway" property, but this property is always "0" for non highways. The fix uses another "highway_display" property to filter out non highways.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-2592
=> DBC22-2592: fixed highway filter does not show non highway cameras

.github/workflows/dev.yml, .github/workflows/test.yml, .github/workflows/uat.yml
https://jira.th.gov.bc.ca/browse/DBC22-2679
I setup imagestreams as a backup in case we are having issues getting images from github, however since all images were going there we were using an excessive amount of space.
This update stops dev from pushing to openshift imagestream, limits test to push only to latest and latest-test tags, and updates UAT to push to latest latest-uat and the release tag.
=> DBC22-2667: Update to Github Actions

compose/frontend/default.conf
https://jira.th.gov.bc.ca/browse/DBC22-2670
CSP change to add flickr and youtube. Unfortunately I needed to add 'unsafe-inline' to style and scripts due to how Flickr does the embed. This will cause a Medium issue in the ZAP scan from a quick test I did.
=> DBC22-2670: Update CSP to allow Flickr/Youtube

src/frontend/src/App.js, src/frontend/src/Components/advisories/AdvisoriesList.js, src/frontend/src/Components/advisories/AdvisoriesList.scss, src/frontend/src/Components/bulletins/BulletinsList.js, src/frontend/src/Components/map/panels/AdvisoriesPanel.js, src/frontend/src/Components/shared/header/Header.js, src/frontend/src/Components/shared/header/Header.scss, src/frontend/src/pages/AdvisoriesListPage.js, src/frontend/src/pages/AdvisoryDetailsPage.js, src/frontend/src/pages/BulletinDetailsPage.js, src/frontend/src/pages/BulletinsListPage.js, src/frontend/src/pages/CamerasListPage.js, src/frontend/src/pages/EventsListPage.js
[DBC22-2465](https://jira.th.gov.bc.ca/browse/DBC22-2465)
Note "unread" class in the list pages are no longer relevant since all advisoires/bulletins are marked as read as soon as we enter the page, per requirement from wireframes. In the same vein, advisoires in the advisory map panel will never show and unread state.
=> DBC22-2465: unread display for advisories/bulletins

src/frontend/src/pages/CamerasListPage.js, src/frontend/src/pages/EventsListPage.js
[DBC22-2661](https://jira.th.gov.bc.ca/browse/DBC22-2661) The ticket only mentions the Camera list, but I found the same behaviour happening on the Delays page. Duplicate ticket for the Delays list might come up later.
=> DBC22-2661: Hiding empty state message before the loading state for cameras and delays.

infrastructure/crunchy-postgres/templates/PostgresCluster.yaml, infrastructure/crunchy-postgres/values-dev.yaml, infrastructure/crunchy-postgres/values-prod.yaml, infrastructure/crunchy-postgres/values-test.yaml, infrastructure/crunchy-postgres/values-uat.yaml
https://jira.th.gov.bc.ca/browse/DBC22-2759
With the upgrade to crunchy operator 5.5.1 we needed to remove the image tag from the helm chart. I manually updated the PostgresCluster object to fix this, but also made the change here so that if we need to rebuild the cluster, it's already fixed.
=> DBC22-2759: Remove direct mapping to image

src/frontend/public/index.html
[DBC22-2654](https://jira.th.gov.bc.ca/browse/DBC22-2654)
https://stackoverflow.com/questions/76026292/why-is-window-innerheight-incorrect-until-i-tap-chrome-android
It would be easier to let Jason test this unless you have the right setup.
=> DBC22-2654: fixed Android Chrome calculating view height incorrectly

src/backend/config/settings/third_party.py
https://jira.th.gov.bc.ca/browse/DBC22-2775
Recent regression that removed the IDP hint. Just adding it back again so it goes directly to BCeID instead of the option page for IDIR or BCeID
=> DBC22-2775: Add idp hint

src/frontend/src/Components/shared/FriendlyTime.scss, src/frontend/src/styles/variables.scss
DBC22-2778: updated color when friendly time hovered.
The fix updated the color hovered on friendly time of camera details page, to have a contrast ratio when hovering on black background.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-2778
=> DBC22-2778: updated color when friendly time hovered

.github/workflows/dev.yml, .github/workflows/test.yml
https://moti-imb.atlassian.net/browse/DBC22-2922
This adds automated smoke testing to the dev & test github actions. 
Once any issues have been ironed out, we will look at adding it to UAT/Prod as well.
=> DBC22-2922: Add automated smoke testing to dev/test

compose/frontend/default.conf
https://moti-imb.atlassian.net/browse/DBC22-2929
As per our discussion we are adjusting the caching of /api/ to ensure users get updates to things like events, webcams, weather, etc a bit quicker.
May result in a bit higher load on django, but it wasn't seeing much load as is.
=> DBC22-2929-2: Update NGINX conf for API

src/frontend/src/Components/map/panels/AdvisoriesPanel.js, src/frontend/src/Components/map/panels/index.js
DBC22-2905: centered the map only for the first loading when advisories are available
The fix moved the logic of the center map to an useEffect hook that only can be executed for the first loading, to avoid the behavior that center the map when the user panning or zooming in/out.
Jira: https://moti-imb.atlassian.net/browse/DBC22-2905
=> DBC22-2905: centered the map only for the first loading when advisories are available

src/frontend/src/Components/report/ReportMap.js, src/frontend/src/Components/report/ReportMap.scss
[DBC22-2831](https://moti-imb.atlassian.net/browse/DBC22-2831)
"The issue with 100vh in mobile Safari being taller than in other browsers like Chrome is due to how mobile Safari handles the viewport height. Mobile Safari includes the height of the browser's UI elements (like the address bar) in the 100vh calculation, which can cause the content to be taller than expected.
To address this, you can use a workaround that calculates the viewport height dynamically using JavaScript and sets a CSS variable. This ensures that the height is consistent across different browsers."
=> DBC22-2831: fixed vh calculation in mobile Safari

src/frontend/src/Components/map/Map.js
DBC22-2926: added combine checks to ensure that mapLayers.current contains at least one property
=> DBC22-2926: added combine checks to ensure that mapLayers.current contains at least one property

src/backend/apps/feed/client.py, src/backend/apps/weather/admin.py, src/backend/apps/weather/serializers.py, src/frontend/src/Components/map/panels/weather/HefPanel.js, src/frontend/src/Components/map/panels/weather/HefPanel.scss, src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.js, src/frontend/src/Components/map/panels/weather/LocalWeatherPanel.scss, src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.js, src/frontend/src/Components/map/panels/weather/RegionalWeatherPanel.scss
DBC22-2932 - Fixed issue where Env Canada now only returns URL in each event which broke the displaying of events on the site (requires an API fix from the SAWSx team which is in their dev env right now. Expected to be in their prod in mid-Dec)
DBC22-2948 - Display multiple warnings on two rows instead of side by side, now each with their own details link.
DBC22-2987 - Updated styling show Highway Name/Number is on separate line of Highway Description. Also added "Courtesy of Environment Canada" text to the bottom.
DBC22-3007 - Footer not staying at bottom of the screen for MOTI weather. Also fixed for Regional Weather
DBC22-3006 - Forecasts mentioned when there are no forecasts
DBC22-3005 - Weathernet time in red
While doing this work I also ensured that weather alerts show on high …
=> DBC22-2932, 2948, 2987, 3007, 3006, 3005: Updates to Env Canada Alerts

.github/workflows/prod.yml, infrastructure/_static/templates/static-deployment.yaml, infrastructure/_static/values.yaml, infrastructure/main/values-dev.yaml, infrastructure/main/values-prod.yaml, infrastructure/main/values-test.yaml, infrastructure/main/values-uat.yaml, infrastructure/main/values.yaml
https://moti-imb.atlassian.net/browse/DBC22-2621
Update HELM chart for static to add a new env variable called RELEASE. This will only be populated in prod with the Github Release Name.
=> DBC22-2621: Update workflow to include RELEASE

compose/frontend/entrypoint, src/frontend/src/Modal.js, src/frontend/src/Modal.scss, src/frontend/src/env.js
Adds the value of environment variables DEPLOYMENT_TAG and RELEASE to the auth modal in a visually inconspicuous way.
=> DBC22-2621

src/backend/apps/authentication/serializers.py, src/backend/apps/shared/fields.py, src/backend/apps/shared/serializers.py
This PR implements a serializer mixin and custom field, for use with model serializers.  The mixin causes DRF to use the custom field instead of DRF's CharField for model char/text fields.  The custom field runs Django's strip_tags on input and output.
=> DBC22-2721 Filter user input through strip_tags

src/frontend/src/Components/map/helpers/map.js
DBC22-3025: check if mapRef is not undefined before using it
=> DBC22-3025: check if mapRef is not undefined before using it

src/frontend/src/Components/events/EventCard.js, src/frontend/src/Components/events/EventsTable.js, src/frontend/src/Components/events/EventsTable.scss, src/frontend/src/pages/EventsListPage.js, src/frontend/src/pages/EventsListPage.scss, src/frontend/src/styles/variables.scss
Bugfixes for the following items:
1. Fix incorrect event table divider colour (James indicated `$Divider` could be changed, rather than just applying a specific colour for the event table
2. Remove the over colour for events when the header is clicked
3. Use the card header for the IntersectionObserver rather than the entire card, which is consistent with the table
4. Move the `View on Map` to a third row for the event table
5. Make the `X updates available` pills clickable
6. Adjust the IntersectionObserver `rootMargin` and `threshold`
=> DBC22-3050

src/frontend/src/Components/map/helpers/index.js, src/frontend/src/Components/map/helpers/spatial.js, src/frontend/src/Components/routing/RouteDetails.js, src/frontend/src/Components/routing/RouteSearch.js
DBC22-3047: show single route if the fastest route is the same as the shortest route
The fix calculates route distance between the fastest and the shortest, to determine if the shortest route should be pushed to the routes list when searching route. When the user clicks "View on map", the searched routes will be filtered depending on if the fastest and shortest are the same or not.
=> DBC22-3047: show single route if the fastest route is the same as the shortest route

src/frontend/src/Components/routing/DistanceLabels.js, src/frontend/src/Components/routing/RouteDetails.js
[DBC22-3058](https://moti-imb.atlassian.net/browse/DBC22-3058)
This was a regression that occured when we reworked RouteDetails to use workers. Ferry data was "hardcoded" and sent into it as a prop, was left out when we reworked events data.
=> DBC22-3058: ferries processed separately from events in route details

src/frontend/src/Components/routing/RouteDetails.scss
The save button's z-index was below the containing div's, which caught the click event.  Increasing the z-index resolves the issue.
=> DBC22-3135 Save button for routes doesn't work

src/backend/apps/cms/views.py, src/frontend/src/Components/advisories/AdvisoriesList.js
[DBC22-3003](https://moti-imb.atlassian.net/browse/DBC22-3003)
Also fixed having to click back button twice when navigated from advisories panel - same issue as the list when we used # in the link.
=> DBC22-3003: use slugs for advisory urls

.github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/test.yml, .github/workflows/uat.yml
Ubuntu-latest image removed the Github action for oc (https://github.com/actions/runner-images/issues/10636)
I added a new step to install the latest version of oc tool so that it would run again.
This commit will need to be cherry-picked into the release branches as UAT and PROD releases will fail without this fix.
=> DBC-3196: Add oc installer in github actions

src/backend/apps/authentication/views.py, src/backend/apps/shared/views.py, src/frontend/src/App.js, src/frontend/src/pages/AccountPage.js, src/frontend/src/pages/AccountPage.scss, src/frontend/src/pages/SavedRoutesPage.js, src/frontend/src/pages/SavedRoutesPage.scss, src/frontend/src/pages/VerifyEmailPage.js, src/frontend/src/pages/VerifyEmailPage.scss, src/frontend/src/styles/variables.scss
[DBC22-2869](https://moti-imb.atlassian.net/browse/DBC22-2869)
=> DBC22-2869: FE integration in saved route and account pages

src/frontend/src/Components/data/locations.js
https://moti-imb.atlassian.net/browse/DBC22-3187
This changes the parameters that get sent to the geocoder to use the new fuzzyMatch parameter (which looks to give better results). It also sets exactSpelling to false since that flag looks like it will provide much worse results than what we are currently getting.
This change will be required before the Geocoder 4.5 prod release on Jan 20th.
If this fix is not in prod on the 20th, the results will become almost unusable since it will return things like schools instead of cities
=> DBC22-3187: Add FuzzyMatch Parameter for geocoder

src/frontend/src/pages/CameraDetailsPage.js
DBC22-3293: added missing event handler for camera details page
=> DBC22-3293: added missing event handler for camera details page

src/frontend/src/Components/cameras/CameraCard.js, src/frontend/src/pages/CamerasListPage.js
DBC22-3302: fixed the issue that camera does not show up when it's not a default camera
When searching for a camera that is not the default camera in the processed camera list, the search result previously showed the default camera instead. This fix addresses the issue by updating the processed camera list for the search. It adds any potentially matching cameras to the list before performing the search. The fix also updated the search function to improve its logic, making it more accurate and easier to understand.
=> DBC22-3302: fixed the issue that camera does not show up when it's not a default camera

src/backend/apps/event/enums.py
[DBC22-3320](https://moti-imb.atlassian.net/browse/DBC22-3320)
When we build the update dictionary, we are passing in null value(instead of missing key for default value) for event_sub_type which can only be a string. This will cause the event to be deleted every other run as if the event didn't exist in the data API, which will then cause update emails to be repeated every other call as the event gets re-created again after deletion from the last call.
Since we're not using the value anywhere on the front end or backend, I've opted to remove this from the update attribute list altogether.
=> DBC22-3320: removed sub type from EVENT_UPDATE_FIELDS

src/frontend/src/Components/map/Map.js
DBC22-3349: Avoided to show camera icon when page refreshed.
This fix checks if the user is refreshing the page or clicked an icon on the map to show the active icon properly.
=> DBC22-3349: Avoided to show camera icon when page refreshed

src/frontend/src/Components/map/MapWrapper.js, src/frontend/src/Components/report/ReportMap.js
DBC22-3567: zoom out report map when page loaded
The code change also included a fix of loading restStops error.
=> DBC22-3567: zoom out report map when page loaded

src/backend/apps/ferry/views.py, src/frontend/src/Components/map/Map.js
DBC22-3718: removed duplicated ferries to avoid set styling failure
=> DBC22-3718: removed duplicated ferries to avoid set styling failure

compose/frontend/Dockerfile, compose/frontend/StaticBuild, compose/frontend/default.conf, compose/frontend/legacy_redirects.conf, compose/openshiftjobs/scripts/analyzeexportlogs.sh, infrastructure/README.md, infrastructure/main/charts/static/templates/static-route.yaml, infrastructure/main/values-dev.yaml, infrastructure/main/values-prod.yaml, infrastructure/main/values-test.yaml, infrastructure/main/values-uat.yaml
https://moti-imb.atlassian.net/browse/DBC22-3837
This will setup methods to redirect all the .com .info .org .net requests as well as drivebc.ca all to www.drivebc.ca
path redirects include:
/cvrp, /rahp, /mobile, /directions.html, /chainup.php
The chainup redirect currently goes to a url that is not setup yet: https://$http_host/?type=route&layers=chainups. Once we have that this will need to be modified.
I also updated the log format to include $host so we can seem amount of redirects from those domains. Had to update goaccess log format as well with that change.
=> DBC22-3837: Domain and path redirects

compose/frontend/default.conf
This fixes the issue where deleted advisories still get results from nginx. Now if the backend returns a 404 it will remove the stale cache object instead of continuing to serve the stale object.
=> DBC22-3437: Expire cache when backend returns 404

compose/frontend/legacy_redirects.conf
Fix regex for /mobile redirect so it matches on /mobile and /mobile/<...>
=> DBC22-3837: Fix mobile legacy redirect

src/frontend/src/Components/routing/RouteSearch.js
DBC22-3855: separated useEffect on searchLocationFrom and searchLocationTo to make sure the hook can be called whenever either of the values was updated.
=> DBC22-3855: separated useEffect on searchLocationFrom and searchLocationTo

compose/backend/Dockerfile
Was looking to reduce the size of the django image a bit as it was 1.56GB. Switched to python:3.13-slim and now it looks to be about ~700MB.
This also reduces security vulnerabilities in the image itself from 4 high, 5 med, 145 low to just 26 low.
I tested the image in dev and it looked to function as expected. If we do start noticing any strange issues, very easy to rollback to the full image.
=> DBC22-3987: Update dockerfile for django

src/backend/apps/authentication/adapters.py, src/backend/config/settings/django.py, src/backend/config/settings/third_party.py, src/backend/config/urls.py, src/backend/templates/socialaccount/login.html
This change enables the use of Keycloak's logout endpoint to kill a user's BCeID/IDIR session at Keycloak, so that on signing into the site again, the user is again challenged for credentials.
=> DBC22-3289 BCeID/IDIR Logout

src/backend/config/admin.py, src/backend/templates/admin/index.html
The other day Russel asked for some additional stats around users such as users with notifications enabled. I was able to pull via some SQL statements, but I figured since you already added some basic stats to the admin panel, I would just expand on those so they are even easier to pull in the future.
=> DBC22-4007: Improve user stats

src/frontend/src/Components/report/ReportMap.scss
Fixes the map not being visible in RAHP maps when user is on mobile in landscape mode.  Caused because page is too short to display map with auto height, so map doesn't render, so page height is not increased to include map.  Fixed by adding min-height to map-wrapper.
=> DBC22-2830 RAHP Map not visible in landscape

src/frontend/src/Components/shared/header/UserNavigation.scss
Puts a max-height on the user menu and adds overflow-y scrollable to it so that when the screen is short enough to cut it off, the menu becomes scrollable.
=> DBC22-4062 Make user menu scrollable

src/backend/apps/event/enums.py
DBC22-2259: added display_category to event diff fields to avoid future events can't be updated
=> DBC22-2259: added display_category to event diff fields to avoid future events can't be updated

src/frontend/src/Components/shared/Filters.js, src/frontend/src/pages/EventsListPage.js
Use of callback in Filter and events list was creating a race condition causing filter state to be out of sync in the events list.  Removed callback mechanism (not used elsewhere) and changed event list to use mapContext, and for Filter to update mapcontext in a way reflecting nested changes.
=> DBC22-4015 Delays list not reflecting changed filters on load

src/frontend/src/Modal.js
The presence of a `next` parameter in the sign out form was preventing the call to .get_redirect_logout_url, which sends the user to the auth server to have their session terminated.
=> DBC22-3289 BCEID not routing through logout

src/backend/apps/event/models.py
The conditional where we generate a polygon for road conditions was not allowing weather conditions (though in setting display category we accept either ROAD_CONDITION or WEATHER_CONDITION).  Added WEATHER_CONDITION to possible values for polygon generation.
=> DBC22-4112 Road conditions not showing width

src/frontend/src/Components/map/panels/CamPanel.js
Automatically updating the image (and triggering the updated message) requires the image to have a data attribute set to the current camIndex.  This attribute was not being set on initially viewing the camera because the useEffect for setting it when camIndex changes was not being executed.  Hard coding the initial index to 0 (the default state for camIndex) resolves the issue.
=> DBC22-4132 Cam panel not updating

compose/frontend/default.conf
This fixes an issue where it was up to the browser to determine how long to keep index.html in cache.
This sometimes caused issues during releases because a browser may have cached the file, but now main.js and the other files don't work anymore which would prevent the user from using the site.
This updated header sets `cache-control: no-cache, must-revalidate, max-age=0` so that the browser will revalidate it on each load. Typically it will just get a 304, but if there are changes it will pull down the new file.
NOTE: I would release this change on it's own before the next release so that when we do the next release we don't break the site for users that had the file cached.
=> DBC22-4324: Update caching header for index.html
